/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YamlRouteImport } from './routes/yaml'
import { Route as XmlJsonRouteImport } from './routes/xml-json'
import { Route as XmlRouteImport } from './routes/xml'
import { Route as WorldClockRouteImport } from './routes/world-clock'
import { Route as WebrtcDiagnosticsRouteImport } from './routes/webrtc-diagnostics'
import { Route as WebpGifRouteImport } from './routes/webp-gif'
import { Route as WebauthnDebuggerRouteImport } from './routes/webauthn-debugger'
import { Route as VideoTrimmerRouteImport } from './routes/video-trimmer'
import { Route as VideoEditorRouteImport } from './routes/video-editor'
import { Route as VideoAnimationRouteImport } from './routes/video-animation'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UserAgentRouteImport } from './routes/user-agent'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as UnixPermissionsRouteImport } from './routes/unix-permissions'
import { Route as UnitConverterRouteImport } from './routes/unit-converter'
import { Route as UnicodeRouteImport } from './routes/unicode'
import { Route as TravelCostRouteImport } from './routes/travel-cost'
import { Route as TraceContextRouteImport } from './routes/trace-context'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as TextRouteImport } from './routes/text'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as TableConvertRouteImport } from './routes/table-convert'
import { Route as SvgToolkitRouteImport } from './routes/svg-toolkit'
import { Route as SubtitleEditorRouteImport } from './routes/subtitle-editor'
import { Route as SqlPlaygroundRouteImport } from './routes/sql-playground'
import { Route as SqlDataRouteImport } from './routes/sql-data'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as SocialInsuranceRouteImport } from './routes/social-insurance'
import { Route as SizeConverterRouteImport } from './routes/size-converter'
import { Route as SettingsPreferencesRouteImport } from './routes/settings-preferences'
import { Route as SettingsDataRouteImport } from './routes/settings-data'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoFilesRouteImport } from './routes/seo-files'
import { Route as ScreenRecorderRouteImport } from './routes/screen-recorder'
import { Route as SalaryTaxRouteImport } from './routes/salary-tax'
import { Route as Rot13RouteImport } from './routes/rot13'
import { Route as RmbUppercaseRouteImport } from './routes/rmb-uppercase'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as RecipeScaleRouteImport } from './routes/recipe-scale'
import { Route as RealtimeDebuggerRouteImport } from './routes/realtime-debugger'
import { Route as RandomPickerRouteImport } from './routes/random-picker'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as PwaIconsRouteImport } from './routes/pwa-icons'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PdfToolkitRouteImport } from './routes/pdf-toolkit'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as PaceCalculatorRouteImport } from './routes/pace-calculator'
import { Route as OpenapiRouteImport } from './routes/openapi'
import { Route as OgPreviewRouteImport } from './routes/og-preview'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as NumberBaseRouteImport } from './routes/number-base'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MockDataRouteImport } from './routes/mock-data'
import { Route as MarkdownRouteImport } from './routes/markdown'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonRouteImport } from './routes/json'
import { Route as JsRouteImport } from './routes/js'
import { Route as Ipv6RouteImport } from './routes/ipv6'
import { Route as IpLookupRouteImport } from './routes/ip-lookup'
import { Route as ImagePrivacyRouteImport } from './routes/image-privacy'
import { Route as ImagePaletteRouteImport } from './routes/image-palette'
import { Route as ImageCompareRouteImport } from './routes/image-compare'
import { Route as ImageRouteImport } from './routes/image'
import { Route as IdPhotoRouteImport } from './routes/id-photo'
import { Route as IcsGeneratorRouteImport } from './routes/ics-generator'
import { Route as HttpStatusRouteImport } from './routes/http-status'
import { Route as HttpRequestRouteImport } from './routes/http-request'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as HomeEnergyRouteImport } from './routes/home-energy'
import { Route as HomeBudgetRouteImport } from './routes/home-budget'
import { Route as HmacRouteImport } from './routes/hmac'
import { Route as HexInspectorRouteImport } from './routes/hex-inspector'
import { Route as HashRouteImport } from './routes/hash'
import { Route as HarAnalyzerRouteImport } from './routes/har-analyzer'
import { Route as GushiNamerRouteImport } from './routes/gushi-namer'
import { Route as GradientStudioRouteImport } from './routes/gradient-studio'
import { Route as GitToolRouteImport } from './routes/git-tool'
import { Route as GeometryCalculatorRouteImport } from './routes/geometry-calculator'
import { Route as FontRouteImport } from './routes/font'
import { Route as FinanceCalculatorRouteImport } from './routes/finance-calculator'
import { Route as EnvRouteImport } from './routes/env'
import { Route as EmojiPickerRouteImport } from './routes/emoji-picker'
import { Route as EmailHeadersRouteImport } from './routes/email-headers'
import { Route as DockerComposeRouteImport } from './routes/docker-compose'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DatetimeRouteImport } from './routes/datetime'
import { Route as DateCalculatorRouteImport } from './routes/date-calculator'
import { Route as CurlConverterRouteImport } from './routes/curl-converter'
import { Route as CsvConvertRouteImport } from './routes/csv-convert'
import { Route as CssUnitRouteImport } from './routes/css-unit'
import { Route as CssTailwindRouteImport } from './routes/css-tailwind'
import { Route as CssShadowRouteImport } from './routes/css-shadow'
import { Route as CssLayoutRouteImport } from './routes/css-layout'
import { Route as CssAnimationRouteImport } from './routes/css-animation'
import { Route as CssRouteImport } from './routes/css'
import { Route as CspRouteImport } from './routes/csp'
import { Route as CronRouteImport } from './routes/cron'
import { Route as CorsRouteImport } from './routes/cors'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContrastRouteImport } from './routes/contrast'
import { Route as ColorConverterRouteImport } from './routes/color-converter'
import { Route as CipherRouteImport } from './routes/cipher'
import { Route as CidrRouteImport } from './routes/cidr'
import { Route as CertificateToolRouteImport } from './routes/certificate-tool'
import { Route as BundleInspectorRouteImport } from './routes/bundle-inspector'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as BillSplitRouteImport } from './routes/bill-split'
import { Route as BatchFilesRouteImport } from './routes/batch-files'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as AudioRecorderRouteImport } from './routes/audio-recorder'
import { Route as AudioEditorRouteImport } from './routes/audio-editor'
import { Route as AspectRatioRouteImport } from './routes/aspect-ratio'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'

const YamlRoute = YamlRouteImport.update({
  id: '/yaml',
  path: '/yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlJsonRoute = XmlJsonRouteImport.update({
  id: '/xml-json',
  path: '/xml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlRoute = XmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldClockRoute = WorldClockRouteImport.update({
  id: '/world-clock',
  path: '/world-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const WebrtcDiagnosticsRoute = WebrtcDiagnosticsRouteImport.update({
  id: '/webrtc-diagnostics',
  path: '/webrtc-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const WebpGifRoute = WebpGifRouteImport.update({
  id: '/webp-gif',
  path: '/webp-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const WebauthnDebuggerRoute = WebauthnDebuggerRouteImport.update({
  id: '/webauthn-debugger',
  path: '/webauthn-debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoTrimmerRoute = VideoTrimmerRouteImport.update({
  id: '/video-trimmer',
  path: '/video-trimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoEditorRoute = VideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoAnimationRoute = VideoAnimationRouteImport.update({
  id: '/video-animation',
  path: '/video-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgentRoute = UserAgentRouteImport.update({
  id: '/user-agent',
  path: '/user-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const UnixPermissionsRoute = UnixPermissionsRouteImport.update({
  id: '/unix-permissions',
  path: '/unix-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UnicodeRoute = UnicodeRouteImport.update({
  id: '/unicode',
  path: '/unicode',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelCostRoute = TravelCostRouteImport.update({
  id: '/travel-cost',
  path: '/travel-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceContextRoute = TraceContextRouteImport.update({
  id: '/trace-context',
  path: '/trace-context',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const TableConvertRoute = TableConvertRouteImport.update({
  id: '/table-convert',
  path: '/table-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgToolkitRoute = SvgToolkitRouteImport.update({
  id: '/svg-toolkit',
  path: '/svg-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtitleEditorRoute = SubtitleEditorRouteImport.update({
  id: '/subtitle-editor',
  path: '/subtitle-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlPlaygroundRoute = SqlPlaygroundRouteImport.update({
  id: '/sql-playground',
  path: '/sql-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlDataRoute = SqlDataRouteImport.update({
  id: '/sql-data',
  path: '/sql-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialInsuranceRoute = SocialInsuranceRouteImport.update({
  id: '/social-insurance',
  path: '/social-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeConverterRoute = SizeConverterRouteImport.update({
  id: '/size-converter',
  path: '/size-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings-preferences',
  path: '/settings-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings-data',
  path: '/settings-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoFilesRoute = SeoFilesRouteImport.update({
  id: '/seo-files',
  path: '/seo-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRecorderRoute = ScreenRecorderRouteImport.update({
  id: '/screen-recorder',
  path: '/screen-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryTaxRoute = SalaryTaxRouteImport.update({
  id: '/salary-tax',
  path: '/salary-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const Rot13Route = Rot13RouteImport.update({
  id: '/rot13',
  path: '/rot13',
  getParentRoute: () => rootRouteImport,
} as any)
const RmbUppercaseRoute = RmbUppercaseRouteImport.update({
  id: '/rmb-uppercase',
  path: '/rmb-uppercase',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeScaleRoute = RecipeScaleRouteImport.update({
  id: '/recipe-scale',
  path: '/recipe-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeDebuggerRoute = RealtimeDebuggerRouteImport.update({
  id: '/realtime-debugger',
  path: '/realtime-debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomPickerRoute = RandomPickerRouteImport.update({
  id: '/random-picker',
  path: '/random-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaIconsRoute = PwaIconsRouteImport.update({
  id: '/pwa-icons',
  path: '/pwa-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolkitRoute = PdfToolkitRouteImport.update({
  id: '/pdf-toolkit',
  path: '/pdf-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaceCalculatorRoute = PaceCalculatorRouteImport.update({
  id: '/pace-calculator',
  path: '/pace-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiRoute = OpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPreviewRoute = OgPreviewRouteImport.update({
  id: '/og-preview',
  path: '/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberBaseRoute = NumberBaseRouteImport.update({
  id: '/number-base',
  path: '/number-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDataRoute = MockDataRouteImport.update({
  id: '/mock-data',
  path: '/mock-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownRoute = MarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const JsRoute = JsRouteImport.update({
  id: '/js',
  path: '/js',
  getParentRoute: () => rootRouteImport,
} as any)
const Ipv6Route = Ipv6RouteImport.update({
  id: '/ipv6',
  path: '/ipv6',
  getParentRoute: () => rootRouteImport,
} as any)
const IpLookupRoute = IpLookupRouteImport.update({
  id: '/ip-lookup',
  path: '/ip-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagePrivacyRoute = ImagePrivacyRouteImport.update({
  id: '/image-privacy',
  path: '/image-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagePaletteRoute = ImagePaletteRouteImport.update({
  id: '/image-palette',
  path: '/image-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompareRoute = ImageCompareRouteImport.update({
  id: '/image-compare',
  path: '/image-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const IdPhotoRoute = IdPhotoRouteImport.update({
  id: '/id-photo',
  path: '/id-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const IcsGeneratorRoute = IcsGeneratorRouteImport.update({
  id: '/ics-generator',
  path: '/ics-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpRequestRoute = HttpRequestRouteImport.update({
  id: '/http-request',
  path: '/http-request',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeEnergyRoute = HomeEnergyRouteImport.update({
  id: '/home-energy',
  path: '/home-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBudgetRoute = HomeBudgetRouteImport.update({
  id: '/home-budget',
  path: '/home-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const HmacRoute = HmacRouteImport.update({
  id: '/hmac',
  path: '/hmac',
  getParentRoute: () => rootRouteImport,
} as any)
const HexInspectorRoute = HexInspectorRouteImport.update({
  id: '/hex-inspector',
  path: '/hex-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const HarAnalyzerRoute = HarAnalyzerRouteImport.update({
  id: '/har-analyzer',
  path: '/har-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const GushiNamerRoute = GushiNamerRouteImport.update({
  id: '/gushi-namer',
  path: '/gushi-namer',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientStudioRoute = GradientStudioRouteImport.update({
  id: '/gradient-studio',
  path: '/gradient-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const GitToolRoute = GitToolRouteImport.update({
  id: '/git-tool',
  path: '/git-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryCalculatorRoute = GeometryCalculatorRouteImport.update({
  id: '/geometry-calculator',
  path: '/geometry-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FontRoute = FontRouteImport.update({
  id: '/font',
  path: '/font',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCalculatorRoute = FinanceCalculatorRouteImport.update({
  id: '/finance-calculator',
  path: '/finance-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvRoute = EnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiPickerRoute = EmojiPickerRouteImport.update({
  id: '/emoji-picker',
  path: '/emoji-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailHeadersRoute = EmailHeadersRouteImport.update({
  id: '/email-headers',
  path: '/email-headers',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerComposeRoute = DockerComposeRouteImport.update({
  id: '/docker-compose',
  path: '/docker-compose',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DatetimeRoute = DatetimeRouteImport.update({
  id: '/datetime',
  path: '/datetime',
  getParentRoute: () => rootRouteImport,
} as any)
const DateCalculatorRoute = DateCalculatorRouteImport.update({
  id: '/date-calculator',
  path: '/date-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CurlConverterRoute = CurlConverterRouteImport.update({
  id: '/curl-converter',
  path: '/curl-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvConvertRoute = CsvConvertRouteImport.update({
  id: '/csv-convert',
  path: '/csv-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CssUnitRoute = CssUnitRouteImport.update({
  id: '/css-unit',
  path: '/css-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const CssTailwindRoute = CssTailwindRouteImport.update({
  id: '/css-tailwind',
  path: '/css-tailwind',
  getParentRoute: () => rootRouteImport,
} as any)
const CssShadowRoute = CssShadowRouteImport.update({
  id: '/css-shadow',
  path: '/css-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const CssLayoutRoute = CssLayoutRouteImport.update({
  id: '/css-layout',
  path: '/css-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CssAnimationRoute = CssAnimationRouteImport.update({
  id: '/css-animation',
  path: '/css-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const CssRoute = CssRouteImport.update({
  id: '/css',
  path: '/css',
  getParentRoute: () => rootRouteImport,
} as any)
const CspRoute = CspRouteImport.update({
  id: '/csp',
  path: '/csp',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsRoute = CorsRouteImport.update({
  id: '/cors',
  path: '/cors',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrastRoute = ContrastRouteImport.update({
  id: '/contrast',
  path: '/contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorConverterRoute = ColorConverterRouteImport.update({
  id: '/color-converter',
  path: '/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CipherRoute = CipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => rootRouteImport,
} as any)
const CidrRoute = CidrRouteImport.update({
  id: '/cidr',
  path: '/cidr',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateToolRoute = CertificateToolRouteImport.update({
  id: '/certificate-tool',
  path: '/certificate-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleInspectorRoute = BundleInspectorRouteImport.update({
  id: '/bundle-inspector',
  path: '/bundle-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const BillSplitRoute = BillSplitRouteImport.update({
  id: '/bill-split',
  path: '/bill-split',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchFilesRoute = BatchFilesRouteImport.update({
  id: '/batch-files',
  path: '/batch-files',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRecorderRoute = AudioRecorderRouteImport.update({
  id: '/audio-recorder',
  path: '/audio-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioEditorRoute = AudioEditorRouteImport.update({
  id: '/audio-editor',
  path: '/audio-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AspectRatioRoute = AspectRatioRouteImport.update({
  id: '/aspect-ratio',
  path: '/aspect-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-editor': typeof AudioEditorRoute
  '/audio-recorder': typeof AudioRecorderRoute
  '/base64': typeof Base64Route
  '/batch-files': typeof BatchFilesRoute
  '/bill-split': typeof BillSplitRoute
  '/bmi': typeof BmiRoute
  '/bundle-inspector': typeof BundleInspectorRoute
  '/certificate-tool': typeof CertificateToolRoute
  '/cidr': typeof CidrRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/cron': typeof CronRoute
  '/csp': typeof CspRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-shadow': typeof CssShadowRoute
  '/css-tailwind': typeof CssTailwindRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/curl-converter': typeof CurlConverterRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/dns': typeof DnsRoute
  '/docker-compose': typeof DockerComposeRoute
  '/email-headers': typeof EmailHeadersRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/env': typeof EnvRoute
  '/finance-calculator': typeof FinanceCalculatorRoute
  '/font': typeof FontRoute
  '/geometry-calculator': typeof GeometryCalculatorRoute
  '/git-tool': typeof GitToolRoute
  '/gradient-studio': typeof GradientStudioRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/har-analyzer': typeof HarAnalyzerRoute
  '/hash': typeof HashRoute
  '/hex-inspector': typeof HexInspectorRoute
  '/hmac': typeof HmacRoute
  '/home-budget': typeof HomeBudgetRoute
  '/home-energy': typeof HomeEnergyRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ics-generator': typeof IcsGeneratorRoute
  '/id-photo': typeof IdPhotoRoute
  '/image': typeof ImageRoute
  '/image-compare': typeof ImageCompareRoute
  '/image-palette': typeof ImagePaletteRoute
  '/image-privacy': typeof ImagePrivacyRoute
  '/ip-lookup': typeof IpLookupRoute
  '/ipv6': typeof Ipv6Route
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mock-data': typeof MockDataRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/oauth': typeof OauthRoute
  '/og-preview': typeof OgPreviewRoute
  '/openapi': typeof OpenapiRoute
  '/pace-calculator': typeof PaceCalculatorRoute
  '/password': typeof PasswordRoute
  '/pdf-toolkit': typeof PdfToolkitRoute
  '/pipeline': typeof PipelineRoute
  '/pwa-icons': typeof PwaIconsRoute
  '/qrcode': typeof QrcodeRoute
  '/random-picker': typeof RandomPickerRoute
  '/realtime-debugger': typeof RealtimeDebuggerRoute
  '/recipe-scale': typeof RecipeScaleRoute
  '/regex': typeof RegexRoute
  '/rmb-uppercase': typeof RmbUppercaseRoute
  '/rot13': typeof Rot13Route
  '/salary-tax': typeof SalaryTaxRoute
  '/screen-recorder': typeof ScreenRecorderRoute
  '/seo-files': typeof SeoFilesRoute
  '/settings': typeof SettingsRoute
  '/settings-data': typeof SettingsDataRoute
  '/settings-preferences': typeof SettingsPreferencesRoute
  '/size-converter': typeof SizeConverterRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-data': typeof SqlDataRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/subtitle-editor': typeof SubtitleEditorRoute
  '/svg-toolkit': typeof SvgToolkitRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/totp': typeof TotpRoute
  '/trace-context': typeof TraceContextRoute
  '/travel-cost': typeof TravelCostRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/unix-permissions': typeof UnixPermissionsRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-animation': typeof VideoAnimationRoute
  '/video-editor': typeof VideoEditorRoute
  '/video-trimmer': typeof VideoTrimmerRoute
  '/webauthn-debugger': typeof WebauthnDebuggerRoute
  '/webp-gif': typeof WebpGifRoute
  '/webrtc-diagnostics': typeof WebrtcDiagnosticsRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-editor': typeof AudioEditorRoute
  '/audio-recorder': typeof AudioRecorderRoute
  '/base64': typeof Base64Route
  '/batch-files': typeof BatchFilesRoute
  '/bill-split': typeof BillSplitRoute
  '/bmi': typeof BmiRoute
  '/bundle-inspector': typeof BundleInspectorRoute
  '/certificate-tool': typeof CertificateToolRoute
  '/cidr': typeof CidrRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/cron': typeof CronRoute
  '/csp': typeof CspRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-shadow': typeof CssShadowRoute
  '/css-tailwind': typeof CssTailwindRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/curl-converter': typeof CurlConverterRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/dns': typeof DnsRoute
  '/docker-compose': typeof DockerComposeRoute
  '/email-headers': typeof EmailHeadersRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/env': typeof EnvRoute
  '/finance-calculator': typeof FinanceCalculatorRoute
  '/font': typeof FontRoute
  '/geometry-calculator': typeof GeometryCalculatorRoute
  '/git-tool': typeof GitToolRoute
  '/gradient-studio': typeof GradientStudioRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/har-analyzer': typeof HarAnalyzerRoute
  '/hash': typeof HashRoute
  '/hex-inspector': typeof HexInspectorRoute
  '/hmac': typeof HmacRoute
  '/home-budget': typeof HomeBudgetRoute
  '/home-energy': typeof HomeEnergyRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ics-generator': typeof IcsGeneratorRoute
  '/id-photo': typeof IdPhotoRoute
  '/image': typeof ImageRoute
  '/image-compare': typeof ImageCompareRoute
  '/image-palette': typeof ImagePaletteRoute
  '/image-privacy': typeof ImagePrivacyRoute
  '/ip-lookup': typeof IpLookupRoute
  '/ipv6': typeof Ipv6Route
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mock-data': typeof MockDataRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/oauth': typeof OauthRoute
  '/og-preview': typeof OgPreviewRoute
  '/openapi': typeof OpenapiRoute
  '/pace-calculator': typeof PaceCalculatorRoute
  '/password': typeof PasswordRoute
  '/pdf-toolkit': typeof PdfToolkitRoute
  '/pipeline': typeof PipelineRoute
  '/pwa-icons': typeof PwaIconsRoute
  '/qrcode': typeof QrcodeRoute
  '/random-picker': typeof RandomPickerRoute
  '/realtime-debugger': typeof RealtimeDebuggerRoute
  '/recipe-scale': typeof RecipeScaleRoute
  '/regex': typeof RegexRoute
  '/rmb-uppercase': typeof RmbUppercaseRoute
  '/rot13': typeof Rot13Route
  '/salary-tax': typeof SalaryTaxRoute
  '/screen-recorder': typeof ScreenRecorderRoute
  '/seo-files': typeof SeoFilesRoute
  '/settings': typeof SettingsRoute
  '/settings-data': typeof SettingsDataRoute
  '/settings-preferences': typeof SettingsPreferencesRoute
  '/size-converter': typeof SizeConverterRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-data': typeof SqlDataRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/subtitle-editor': typeof SubtitleEditorRoute
  '/svg-toolkit': typeof SvgToolkitRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/totp': typeof TotpRoute
  '/trace-context': typeof TraceContextRoute
  '/travel-cost': typeof TravelCostRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/unix-permissions': typeof UnixPermissionsRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-animation': typeof VideoAnimationRoute
  '/video-editor': typeof VideoEditorRoute
  '/video-trimmer': typeof VideoTrimmerRoute
  '/webauthn-debugger': typeof WebauthnDebuggerRoute
  '/webp-gif': typeof WebpGifRoute
  '/webrtc-diagnostics': typeof WebrtcDiagnosticsRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-editor': typeof AudioEditorRoute
  '/audio-recorder': typeof AudioRecorderRoute
  '/base64': typeof Base64Route
  '/batch-files': typeof BatchFilesRoute
  '/bill-split': typeof BillSplitRoute
  '/bmi': typeof BmiRoute
  '/bundle-inspector': typeof BundleInspectorRoute
  '/certificate-tool': typeof CertificateToolRoute
  '/cidr': typeof CidrRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/cron': typeof CronRoute
  '/csp': typeof CspRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-shadow': typeof CssShadowRoute
  '/css-tailwind': typeof CssTailwindRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/curl-converter': typeof CurlConverterRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/dns': typeof DnsRoute
  '/docker-compose': typeof DockerComposeRoute
  '/email-headers': typeof EmailHeadersRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/env': typeof EnvRoute
  '/finance-calculator': typeof FinanceCalculatorRoute
  '/font': typeof FontRoute
  '/geometry-calculator': typeof GeometryCalculatorRoute
  '/git-tool': typeof GitToolRoute
  '/gradient-studio': typeof GradientStudioRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/har-analyzer': typeof HarAnalyzerRoute
  '/hash': typeof HashRoute
  '/hex-inspector': typeof HexInspectorRoute
  '/hmac': typeof HmacRoute
  '/home-budget': typeof HomeBudgetRoute
  '/home-energy': typeof HomeEnergyRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ics-generator': typeof IcsGeneratorRoute
  '/id-photo': typeof IdPhotoRoute
  '/image': typeof ImageRoute
  '/image-compare': typeof ImageCompareRoute
  '/image-palette': typeof ImagePaletteRoute
  '/image-privacy': typeof ImagePrivacyRoute
  '/ip-lookup': typeof IpLookupRoute
  '/ipv6': typeof Ipv6Route
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mock-data': typeof MockDataRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/oauth': typeof OauthRoute
  '/og-preview': typeof OgPreviewRoute
  '/openapi': typeof OpenapiRoute
  '/pace-calculator': typeof PaceCalculatorRoute
  '/password': typeof PasswordRoute
  '/pdf-toolkit': typeof PdfToolkitRoute
  '/pipeline': typeof PipelineRoute
  '/pwa-icons': typeof PwaIconsRoute
  '/qrcode': typeof QrcodeRoute
  '/random-picker': typeof RandomPickerRoute
  '/realtime-debugger': typeof RealtimeDebuggerRoute
  '/recipe-scale': typeof RecipeScaleRoute
  '/regex': typeof RegexRoute
  '/rmb-uppercase': typeof RmbUppercaseRoute
  '/rot13': typeof Rot13Route
  '/salary-tax': typeof SalaryTaxRoute
  '/screen-recorder': typeof ScreenRecorderRoute
  '/seo-files': typeof SeoFilesRoute
  '/settings': typeof SettingsRoute
  '/settings-data': typeof SettingsDataRoute
  '/settings-preferences': typeof SettingsPreferencesRoute
  '/size-converter': typeof SizeConverterRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-data': typeof SqlDataRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/subtitle-editor': typeof SubtitleEditorRoute
  '/svg-toolkit': typeof SvgToolkitRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/totp': typeof TotpRoute
  '/trace-context': typeof TraceContextRoute
  '/travel-cost': typeof TravelCostRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/unix-permissions': typeof UnixPermissionsRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-animation': typeof VideoAnimationRoute
  '/video-editor': typeof VideoEditorRoute
  '/video-trimmer': typeof VideoTrimmerRoute
  '/webauthn-debugger': typeof WebauthnDebuggerRoute
  '/webp-gif': typeof WebpGifRoute
  '/webrtc-diagnostics': typeof WebrtcDiagnosticsRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/aspect-ratio'
    | '/audio-editor'
    | '/audio-recorder'
    | '/base64'
    | '/batch-files'
    | '/bill-split'
    | '/bmi'
    | '/bundle-inspector'
    | '/certificate-tool'
    | '/cidr'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/cron'
    | '/csp'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-shadow'
    | '/css-tailwind'
    | '/css-unit'
    | '/csv-convert'
    | '/curl-converter'
    | '/date-calculator'
    | '/datetime'
    | '/diff'
    | '/dns'
    | '/docker-compose'
    | '/email-headers'
    | '/emoji-picker'
    | '/env'
    | '/finance-calculator'
    | '/font'
    | '/geometry-calculator'
    | '/git-tool'
    | '/gradient-studio'
    | '/gushi-namer'
    | '/har-analyzer'
    | '/hash'
    | '/hex-inspector'
    | '/hmac'
    | '/home-budget'
    | '/home-energy'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ics-generator'
    | '/id-photo'
    | '/image'
    | '/image-compare'
    | '/image-palette'
    | '/image-privacy'
    | '/ip-lookup'
    | '/ipv6'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mock-data'
    | '/mortgage'
    | '/number-base'
    | '/oauth'
    | '/og-preview'
    | '/openapi'
    | '/pace-calculator'
    | '/password'
    | '/pdf-toolkit'
    | '/pipeline'
    | '/pwa-icons'
    | '/qrcode'
    | '/random-picker'
    | '/realtime-debugger'
    | '/recipe-scale'
    | '/regex'
    | '/rmb-uppercase'
    | '/rot13'
    | '/salary-tax'
    | '/screen-recorder'
    | '/seo-files'
    | '/settings'
    | '/settings-data'
    | '/settings-preferences'
    | '/size-converter'
    | '/social-insurance'
    | '/sql'
    | '/sql-data'
    | '/sql-playground'
    | '/subtitle-editor'
    | '/svg-toolkit'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/text-to-speech'
    | '/totp'
    | '/trace-context'
    | '/travel-cost'
    | '/unicode'
    | '/unit-converter'
    | '/unix-permissions'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/video-animation'
    | '/video-editor'
    | '/video-trimmer'
    | '/webauthn-debugger'
    | '/webp-gif'
    | '/webrtc-diagnostics'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/aspect-ratio'
    | '/audio-editor'
    | '/audio-recorder'
    | '/base64'
    | '/batch-files'
    | '/bill-split'
    | '/bmi'
    | '/bundle-inspector'
    | '/certificate-tool'
    | '/cidr'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/cron'
    | '/csp'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-shadow'
    | '/css-tailwind'
    | '/css-unit'
    | '/csv-convert'
    | '/curl-converter'
    | '/date-calculator'
    | '/datetime'
    | '/diff'
    | '/dns'
    | '/docker-compose'
    | '/email-headers'
    | '/emoji-picker'
    | '/env'
    | '/finance-calculator'
    | '/font'
    | '/geometry-calculator'
    | '/git-tool'
    | '/gradient-studio'
    | '/gushi-namer'
    | '/har-analyzer'
    | '/hash'
    | '/hex-inspector'
    | '/hmac'
    | '/home-budget'
    | '/home-energy'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ics-generator'
    | '/id-photo'
    | '/image'
    | '/image-compare'
    | '/image-palette'
    | '/image-privacy'
    | '/ip-lookup'
    | '/ipv6'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mock-data'
    | '/mortgage'
    | '/number-base'
    | '/oauth'
    | '/og-preview'
    | '/openapi'
    | '/pace-calculator'
    | '/password'
    | '/pdf-toolkit'
    | '/pipeline'
    | '/pwa-icons'
    | '/qrcode'
    | '/random-picker'
    | '/realtime-debugger'
    | '/recipe-scale'
    | '/regex'
    | '/rmb-uppercase'
    | '/rot13'
    | '/salary-tax'
    | '/screen-recorder'
    | '/seo-files'
    | '/settings'
    | '/settings-data'
    | '/settings-preferences'
    | '/size-converter'
    | '/social-insurance'
    | '/sql'
    | '/sql-data'
    | '/sql-playground'
    | '/subtitle-editor'
    | '/svg-toolkit'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/text-to-speech'
    | '/totp'
    | '/trace-context'
    | '/travel-cost'
    | '/unicode'
    | '/unit-converter'
    | '/unix-permissions'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/video-animation'
    | '/video-editor'
    | '/video-trimmer'
    | '/webauthn-debugger'
    | '/webp-gif'
    | '/webrtc-diagnostics'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/aspect-ratio'
    | '/audio-editor'
    | '/audio-recorder'
    | '/base64'
    | '/batch-files'
    | '/bill-split'
    | '/bmi'
    | '/bundle-inspector'
    | '/certificate-tool'
    | '/cidr'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/cron'
    | '/csp'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-shadow'
    | '/css-tailwind'
    | '/css-unit'
    | '/csv-convert'
    | '/curl-converter'
    | '/date-calculator'
    | '/datetime'
    | '/diff'
    | '/dns'
    | '/docker-compose'
    | '/email-headers'
    | '/emoji-picker'
    | '/env'
    | '/finance-calculator'
    | '/font'
    | '/geometry-calculator'
    | '/git-tool'
    | '/gradient-studio'
    | '/gushi-namer'
    | '/har-analyzer'
    | '/hash'
    | '/hex-inspector'
    | '/hmac'
    | '/home-budget'
    | '/home-energy'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ics-generator'
    | '/id-photo'
    | '/image'
    | '/image-compare'
    | '/image-palette'
    | '/image-privacy'
    | '/ip-lookup'
    | '/ipv6'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mock-data'
    | '/mortgage'
    | '/number-base'
    | '/oauth'
    | '/og-preview'
    | '/openapi'
    | '/pace-calculator'
    | '/password'
    | '/pdf-toolkit'
    | '/pipeline'
    | '/pwa-icons'
    | '/qrcode'
    | '/random-picker'
    | '/realtime-debugger'
    | '/recipe-scale'
    | '/regex'
    | '/rmb-uppercase'
    | '/rot13'
    | '/salary-tax'
    | '/screen-recorder'
    | '/seo-files'
    | '/settings'
    | '/settings-data'
    | '/settings-preferences'
    | '/size-converter'
    | '/social-insurance'
    | '/sql'
    | '/sql-data'
    | '/sql-playground'
    | '/subtitle-editor'
    | '/svg-toolkit'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/text-to-speech'
    | '/totp'
    | '/trace-context'
    | '/travel-cost'
    | '/unicode'
    | '/unit-converter'
    | '/unix-permissions'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/video-animation'
    | '/video-editor'
    | '/video-trimmer'
    | '/webauthn-debugger'
    | '/webp-gif'
    | '/webrtc-diagnostics'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AspectRatioRoute: typeof AspectRatioRoute
  AudioEditorRoute: typeof AudioEditorRoute
  AudioRecorderRoute: typeof AudioRecorderRoute
  Base64Route: typeof Base64Route
  BatchFilesRoute: typeof BatchFilesRoute
  BillSplitRoute: typeof BillSplitRoute
  BmiRoute: typeof BmiRoute
  BundleInspectorRoute: typeof BundleInspectorRoute
  CertificateToolRoute: typeof CertificateToolRoute
  CidrRoute: typeof CidrRoute
  CipherRoute: typeof CipherRoute
  ColorConverterRoute: typeof ColorConverterRoute
  ContrastRoute: typeof ContrastRoute
  CookieRoute: typeof CookieRoute
  CorsRoute: typeof CorsRoute
  CronRoute: typeof CronRoute
  CspRoute: typeof CspRoute
  CssRoute: typeof CssRoute
  CssAnimationRoute: typeof CssAnimationRoute
  CssLayoutRoute: typeof CssLayoutRoute
  CssShadowRoute: typeof CssShadowRoute
  CssTailwindRoute: typeof CssTailwindRoute
  CssUnitRoute: typeof CssUnitRoute
  CsvConvertRoute: typeof CsvConvertRoute
  CurlConverterRoute: typeof CurlConverterRoute
  DateCalculatorRoute: typeof DateCalculatorRoute
  DatetimeRoute: typeof DatetimeRoute
  DiffRoute: typeof DiffRoute
  DnsRoute: typeof DnsRoute
  DockerComposeRoute: typeof DockerComposeRoute
  EmailHeadersRoute: typeof EmailHeadersRoute
  EmojiPickerRoute: typeof EmojiPickerRoute
  EnvRoute: typeof EnvRoute
  FinanceCalculatorRoute: typeof FinanceCalculatorRoute
  FontRoute: typeof FontRoute
  GeometryCalculatorRoute: typeof GeometryCalculatorRoute
  GitToolRoute: typeof GitToolRoute
  GradientStudioRoute: typeof GradientStudioRoute
  GushiNamerRoute: typeof GushiNamerRoute
  HarAnalyzerRoute: typeof HarAnalyzerRoute
  HashRoute: typeof HashRoute
  HexInspectorRoute: typeof HexInspectorRoute
  HmacRoute: typeof HmacRoute
  HomeBudgetRoute: typeof HomeBudgetRoute
  HomeEnergyRoute: typeof HomeEnergyRoute
  HtmlRoute: typeof HtmlRoute
  HttpRequestRoute: typeof HttpRequestRoute
  HttpStatusRoute: typeof HttpStatusRoute
  IcsGeneratorRoute: typeof IcsGeneratorRoute
  IdPhotoRoute: typeof IdPhotoRoute
  ImageRoute: typeof ImageRoute
  ImageCompareRoute: typeof ImageCompareRoute
  ImagePaletteRoute: typeof ImagePaletteRoute
  ImagePrivacyRoute: typeof ImagePrivacyRoute
  IpLookupRoute: typeof IpLookupRoute
  Ipv6Route: typeof Ipv6Route
  JsRoute: typeof JsRoute
  JsonRoute: typeof JsonRoute
  JwtRoute: typeof JwtRoute
  LoginRoute: typeof LoginRoute
  MarkdownRoute: typeof MarkdownRoute
  MockDataRoute: typeof MockDataRoute
  MortgageRoute: typeof MortgageRoute
  NumberBaseRoute: typeof NumberBaseRoute
  OauthRoute: typeof OauthRoute
  OgPreviewRoute: typeof OgPreviewRoute
  OpenapiRoute: typeof OpenapiRoute
  PaceCalculatorRoute: typeof PaceCalculatorRoute
  PasswordRoute: typeof PasswordRoute
  PdfToolkitRoute: typeof PdfToolkitRoute
  PipelineRoute: typeof PipelineRoute
  PwaIconsRoute: typeof PwaIconsRoute
  QrcodeRoute: typeof QrcodeRoute
  RandomPickerRoute: typeof RandomPickerRoute
  RealtimeDebuggerRoute: typeof RealtimeDebuggerRoute
  RecipeScaleRoute: typeof RecipeScaleRoute
  RegexRoute: typeof RegexRoute
  RmbUppercaseRoute: typeof RmbUppercaseRoute
  Rot13Route: typeof Rot13Route
  SalaryTaxRoute: typeof SalaryTaxRoute
  ScreenRecorderRoute: typeof ScreenRecorderRoute
  SeoFilesRoute: typeof SeoFilesRoute
  SettingsRoute: typeof SettingsRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SizeConverterRoute: typeof SizeConverterRoute
  SocialInsuranceRoute: typeof SocialInsuranceRoute
  SqlRoute: typeof SqlRoute
  SqlDataRoute: typeof SqlDataRoute
  SqlPlaygroundRoute: typeof SqlPlaygroundRoute
  SubtitleEditorRoute: typeof SubtitleEditorRoute
  SvgToolkitRoute: typeof SvgToolkitRoute
  TableConvertRoute: typeof TableConvertRoute
  TemperatureRoute: typeof TemperatureRoute
  TextRoute: typeof TextRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  TotpRoute: typeof TotpRoute
  TraceContextRoute: typeof TraceContextRoute
  TravelCostRoute: typeof TravelCostRoute
  UnicodeRoute: typeof UnicodeRoute
  UnitConverterRoute: typeof UnitConverterRoute
  UnixPermissionsRoute: typeof UnixPermissionsRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UserAgentRoute: typeof UserAgentRoute
  UuidRoute: typeof UuidRoute
  VideoAnimationRoute: typeof VideoAnimationRoute
  VideoEditorRoute: typeof VideoEditorRoute
  VideoTrimmerRoute: typeof VideoTrimmerRoute
  WebauthnDebuggerRoute: typeof WebauthnDebuggerRoute
  WebpGifRoute: typeof WebpGifRoute
  WebrtcDiagnosticsRoute: typeof WebrtcDiagnosticsRoute
  WorldClockRoute: typeof WorldClockRoute
  XmlRoute: typeof XmlRoute
  XmlJsonRoute: typeof XmlJsonRoute
  YamlRoute: typeof YamlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaml': {
      id: '/yaml'
      path: '/yaml'
      fullPath: '/yaml'
      preLoaderRoute: typeof YamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-json': {
      id: '/xml-json'
      path: '/xml-json'
      fullPath: '/xml-json'
      preLoaderRoute: typeof XmlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml': {
      id: '/xml'
      path: '/xml'
      fullPath: '/xml'
      preLoaderRoute: typeof XmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-clock': {
      id: '/world-clock'
      path: '/world-clock'
      fullPath: '/world-clock'
      preLoaderRoute: typeof WorldClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webrtc-diagnostics': {
      id: '/webrtc-diagnostics'
      path: '/webrtc-diagnostics'
      fullPath: '/webrtc-diagnostics'
      preLoaderRoute: typeof WebrtcDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webp-gif': {
      id: '/webp-gif'
      path: '/webp-gif'
      fullPath: '/webp-gif'
      preLoaderRoute: typeof WebpGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webauthn-debugger': {
      id: '/webauthn-debugger'
      path: '/webauthn-debugger'
      fullPath: '/webauthn-debugger'
      preLoaderRoute: typeof WebauthnDebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-trimmer': {
      id: '/video-trimmer'
      path: '/video-trimmer'
      fullPath: '/video-trimmer'
      preLoaderRoute: typeof VideoTrimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-editor': {
      id: '/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof VideoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-animation': {
      id: '/video-animation'
      path: '/video-animation'
      fullPath: '/video-animation'
      preLoaderRoute: typeof VideoAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agent': {
      id: '/user-agent'
      path: '/user-agent'
      fullPath: '/user-agent'
      preLoaderRoute: typeof UserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unix-permissions': {
      id: '/unix-permissions'
      path: '/unix-permissions'
      fullPath: '/unix-permissions'
      preLoaderRoute: typeof UnixPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-converter': {
      id: '/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unicode': {
      id: '/unicode'
      path: '/unicode'
      fullPath: '/unicode'
      preLoaderRoute: typeof UnicodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-cost': {
      id: '/travel-cost'
      path: '/travel-cost'
      fullPath: '/travel-cost'
      preLoaderRoute: typeof TravelCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-context': {
      id: '/trace-context'
      path: '/trace-context'
      fullPath: '/trace-context'
      preLoaderRoute: typeof TraceContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-convert': {
      id: '/table-convert'
      path: '/table-convert'
      fullPath: '/table-convert'
      preLoaderRoute: typeof TableConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-toolkit': {
      id: '/svg-toolkit'
      path: '/svg-toolkit'
      fullPath: '/svg-toolkit'
      preLoaderRoute: typeof SvgToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtitle-editor': {
      id: '/subtitle-editor'
      path: '/subtitle-editor'
      fullPath: '/subtitle-editor'
      preLoaderRoute: typeof SubtitleEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-playground': {
      id: '/sql-playground'
      path: '/sql-playground'
      fullPath: '/sql-playground'
      preLoaderRoute: typeof SqlPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-data': {
      id: '/sql-data'
      path: '/sql-data'
      fullPath: '/sql-data'
      preLoaderRoute: typeof SqlDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-insurance': {
      id: '/social-insurance'
      path: '/social-insurance'
      fullPath: '/social-insurance'
      preLoaderRoute: typeof SocialInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-converter': {
      id: '/size-converter'
      path: '/size-converter'
      fullPath: '/size-converter'
      preLoaderRoute: typeof SizeConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-preferences': {
      id: '/settings-preferences'
      path: '/settings-preferences'
      fullPath: '/settings-preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-data': {
      id: '/settings-data'
      path: '/settings-data'
      fullPath: '/settings-data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-files': {
      id: '/seo-files'
      path: '/seo-files'
      fullPath: '/seo-files'
      preLoaderRoute: typeof SeoFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-recorder': {
      id: '/screen-recorder'
      path: '/screen-recorder'
      fullPath: '/screen-recorder'
      preLoaderRoute: typeof ScreenRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-tax': {
      id: '/salary-tax'
      path: '/salary-tax'
      fullPath: '/salary-tax'
      preLoaderRoute: typeof SalaryTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rot13': {
      id: '/rot13'
      path: '/rot13'
      fullPath: '/rot13'
      preLoaderRoute: typeof Rot13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmb-uppercase': {
      id: '/rmb-uppercase'
      path: '/rmb-uppercase'
      fullPath: '/rmb-uppercase'
      preLoaderRoute: typeof RmbUppercaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-scale': {
      id: '/recipe-scale'
      path: '/recipe-scale'
      fullPath: '/recipe-scale'
      preLoaderRoute: typeof RecipeScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime-debugger': {
      id: '/realtime-debugger'
      path: '/realtime-debugger'
      fullPath: '/realtime-debugger'
      preLoaderRoute: typeof RealtimeDebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-picker': {
      id: '/random-picker'
      path: '/random-picker'
      fullPath: '/random-picker'
      preLoaderRoute: typeof RandomPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa-icons': {
      id: '/pwa-icons'
      path: '/pwa-icons'
      fullPath: '/pwa-icons'
      preLoaderRoute: typeof PwaIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-toolkit': {
      id: '/pdf-toolkit'
      path: '/pdf-toolkit'
      fullPath: '/pdf-toolkit'
      preLoaderRoute: typeof PdfToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pace-calculator': {
      id: '/pace-calculator'
      path: '/pace-calculator'
      fullPath: '/pace-calculator'
      preLoaderRoute: typeof PaceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-preview': {
      id: '/og-preview'
      path: '/og-preview'
      fullPath: '/og-preview'
      preLoaderRoute: typeof OgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-base': {
      id: '/number-base'
      path: '/number-base'
      fullPath: '/number-base'
      preLoaderRoute: typeof NumberBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-data': {
      id: '/mock-data'
      path: '/mock-data'
      fullPath: '/mock-data'
      preLoaderRoute: typeof MockDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js': {
      id: '/js'
      path: '/js'
      fullPath: '/js'
      preLoaderRoute: typeof JsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipv6': {
      id: '/ipv6'
      path: '/ipv6'
      fullPath: '/ipv6'
      preLoaderRoute: typeof Ipv6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-lookup': {
      id: '/ip-lookup'
      path: '/ip-lookup'
      fullPath: '/ip-lookup'
      preLoaderRoute: typeof IpLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-privacy': {
      id: '/image-privacy'
      path: '/image-privacy'
      fullPath: '/image-privacy'
      preLoaderRoute: typeof ImagePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-palette': {
      id: '/image-palette'
      path: '/image-palette'
      fullPath: '/image-palette'
      preLoaderRoute: typeof ImagePaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compare': {
      id: '/image-compare'
      path: '/image-compare'
      fullPath: '/image-compare'
      preLoaderRoute: typeof ImageCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-photo': {
      id: '/id-photo'
      path: '/id-photo'
      fullPath: '/id-photo'
      preLoaderRoute: typeof IdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ics-generator': {
      id: '/ics-generator'
      path: '/ics-generator'
      fullPath: '/ics-generator'
      preLoaderRoute: typeof IcsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-status': {
      id: '/http-status'
      path: '/http-status'
      fullPath: '/http-status'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-request': {
      id: '/http-request'
      path: '/http-request'
      fullPath: '/http-request'
      preLoaderRoute: typeof HttpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-energy': {
      id: '/home-energy'
      path: '/home-energy'
      fullPath: '/home-energy'
      preLoaderRoute: typeof HomeEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-budget': {
      id: '/home-budget'
      path: '/home-budget'
      fullPath: '/home-budget'
      preLoaderRoute: typeof HomeBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmac': {
      id: '/hmac'
      path: '/hmac'
      fullPath: '/hmac'
      preLoaderRoute: typeof HmacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hex-inspector': {
      id: '/hex-inspector'
      path: '/hex-inspector'
      fullPath: '/hex-inspector'
      preLoaderRoute: typeof HexInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/har-analyzer': {
      id: '/har-analyzer'
      path: '/har-analyzer'
      fullPath: '/har-analyzer'
      preLoaderRoute: typeof HarAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gushi-namer': {
      id: '/gushi-namer'
      path: '/gushi-namer'
      fullPath: '/gushi-namer'
      preLoaderRoute: typeof GushiNamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient-studio': {
      id: '/gradient-studio'
      path: '/gradient-studio'
      fullPath: '/gradient-studio'
      preLoaderRoute: typeof GradientStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-tool': {
      id: '/git-tool'
      path: '/git-tool'
      fullPath: '/git-tool'
      preLoaderRoute: typeof GitToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry-calculator': {
      id: '/geometry-calculator'
      path: '/geometry-calculator'
      fullPath: '/geometry-calculator'
      preLoaderRoute: typeof GeometryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font': {
      id: '/font'
      path: '/font'
      fullPath: '/font'
      preLoaderRoute: typeof FontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-calculator': {
      id: '/finance-calculator'
      path: '/finance-calculator'
      fullPath: '/finance-calculator'
      preLoaderRoute: typeof FinanceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env': {
      id: '/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof EnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji-picker': {
      id: '/emoji-picker'
      path: '/emoji-picker'
      fullPath: '/emoji-picker'
      preLoaderRoute: typeof EmojiPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-headers': {
      id: '/email-headers'
      path: '/email-headers'
      fullPath: '/email-headers'
      preLoaderRoute: typeof EmailHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker-compose': {
      id: '/docker-compose'
      path: '/docker-compose'
      fullPath: '/docker-compose'
      preLoaderRoute: typeof DockerComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datetime': {
      id: '/datetime'
      path: '/datetime'
      fullPath: '/datetime'
      preLoaderRoute: typeof DatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-calculator': {
      id: '/date-calculator'
      path: '/date-calculator'
      fullPath: '/date-calculator'
      preLoaderRoute: typeof DateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curl-converter': {
      id: '/curl-converter'
      path: '/curl-converter'
      fullPath: '/curl-converter'
      preLoaderRoute: typeof CurlConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-convert': {
      id: '/csv-convert'
      path: '/csv-convert'
      fullPath: '/csv-convert'
      preLoaderRoute: typeof CsvConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-unit': {
      id: '/css-unit'
      path: '/css-unit'
      fullPath: '/css-unit'
      preLoaderRoute: typeof CssUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-tailwind': {
      id: '/css-tailwind'
      path: '/css-tailwind'
      fullPath: '/css-tailwind'
      preLoaderRoute: typeof CssTailwindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-shadow': {
      id: '/css-shadow'
      path: '/css-shadow'
      fullPath: '/css-shadow'
      preLoaderRoute: typeof CssShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-layout': {
      id: '/css-layout'
      path: '/css-layout'
      fullPath: '/css-layout'
      preLoaderRoute: typeof CssLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-animation': {
      id: '/css-animation'
      path: '/css-animation'
      fullPath: '/css-animation'
      preLoaderRoute: typeof CssAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css': {
      id: '/css'
      path: '/css'
      fullPath: '/css'
      preLoaderRoute: typeof CssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp': {
      id: '/csp'
      path: '/csp'
      fullPath: '/csp'
      preLoaderRoute: typeof CspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cors': {
      id: '/cors'
      path: '/cors'
      fullPath: '/cors'
      preLoaderRoute: typeof CorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrast': {
      id: '/contrast'
      path: '/contrast'
      fullPath: '/contrast'
      preLoaderRoute: typeof ContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-converter': {
      id: '/color-converter'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof ColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cipher': {
      id: '/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof CipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidr': {
      id: '/cidr'
      path: '/cidr'
      fullPath: '/cidr'
      preLoaderRoute: typeof CidrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate-tool': {
      id: '/certificate-tool'
      path: '/certificate-tool'
      fullPath: '/certificate-tool'
      preLoaderRoute: typeof CertificateToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle-inspector': {
      id: '/bundle-inspector'
      path: '/bundle-inspector'
      fullPath: '/bundle-inspector'
      preLoaderRoute: typeof BundleInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-split': {
      id: '/bill-split'
      path: '/bill-split'
      fullPath: '/bill-split'
      preLoaderRoute: typeof BillSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-files': {
      id: '/batch-files'
      path: '/batch-files'
      fullPath: '/batch-files'
      preLoaderRoute: typeof BatchFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-recorder': {
      id: '/audio-recorder'
      path: '/audio-recorder'
      fullPath: '/audio-recorder'
      preLoaderRoute: typeof AudioRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-editor': {
      id: '/audio-editor'
      path: '/audio-editor'
      fullPath: '/audio-editor'
      preLoaderRoute: typeof AudioEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspect-ratio': {
      id: '/aspect-ratio'
      path: '/aspect-ratio'
      fullPath: '/aspect-ratio'
      preLoaderRoute: typeof AspectRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AspectRatioRoute: AspectRatioRoute,
  AudioEditorRoute: AudioEditorRoute,
  AudioRecorderRoute: AudioRecorderRoute,
  Base64Route: Base64Route,
  BatchFilesRoute: BatchFilesRoute,
  BillSplitRoute: BillSplitRoute,
  BmiRoute: BmiRoute,
  BundleInspectorRoute: BundleInspectorRoute,
  CertificateToolRoute: CertificateToolRoute,
  CidrRoute: CidrRoute,
  CipherRoute: CipherRoute,
  ColorConverterRoute: ColorConverterRoute,
  ContrastRoute: ContrastRoute,
  CookieRoute: CookieRoute,
  CorsRoute: CorsRoute,
  CronRoute: CronRoute,
  CspRoute: CspRoute,
  CssRoute: CssRoute,
  CssAnimationRoute: CssAnimationRoute,
  CssLayoutRoute: CssLayoutRoute,
  CssShadowRoute: CssShadowRoute,
  CssTailwindRoute: CssTailwindRoute,
  CssUnitRoute: CssUnitRoute,
  CsvConvertRoute: CsvConvertRoute,
  CurlConverterRoute: CurlConverterRoute,
  DateCalculatorRoute: DateCalculatorRoute,
  DatetimeRoute: DatetimeRoute,
  DiffRoute: DiffRoute,
  DnsRoute: DnsRoute,
  DockerComposeRoute: DockerComposeRoute,
  EmailHeadersRoute: EmailHeadersRoute,
  EmojiPickerRoute: EmojiPickerRoute,
  EnvRoute: EnvRoute,
  FinanceCalculatorRoute: FinanceCalculatorRoute,
  FontRoute: FontRoute,
  GeometryCalculatorRoute: GeometryCalculatorRoute,
  GitToolRoute: GitToolRoute,
  GradientStudioRoute: GradientStudioRoute,
  GushiNamerRoute: GushiNamerRoute,
  HarAnalyzerRoute: HarAnalyzerRoute,
  HashRoute: HashRoute,
  HexInspectorRoute: HexInspectorRoute,
  HmacRoute: HmacRoute,
  HomeBudgetRoute: HomeBudgetRoute,
  HomeEnergyRoute: HomeEnergyRoute,
  HtmlRoute: HtmlRoute,
  HttpRequestRoute: HttpRequestRoute,
  HttpStatusRoute: HttpStatusRoute,
  IcsGeneratorRoute: IcsGeneratorRoute,
  IdPhotoRoute: IdPhotoRoute,
  ImageRoute: ImageRoute,
  ImageCompareRoute: ImageCompareRoute,
  ImagePaletteRoute: ImagePaletteRoute,
  ImagePrivacyRoute: ImagePrivacyRoute,
  IpLookupRoute: IpLookupRoute,
  Ipv6Route: Ipv6Route,
  JsRoute: JsRoute,
  JsonRoute: JsonRoute,
  JwtRoute: JwtRoute,
  LoginRoute: LoginRoute,
  MarkdownRoute: MarkdownRoute,
  MockDataRoute: MockDataRoute,
  MortgageRoute: MortgageRoute,
  NumberBaseRoute: NumberBaseRoute,
  OauthRoute: OauthRoute,
  OgPreviewRoute: OgPreviewRoute,
  OpenapiRoute: OpenapiRoute,
  PaceCalculatorRoute: PaceCalculatorRoute,
  PasswordRoute: PasswordRoute,
  PdfToolkitRoute: PdfToolkitRoute,
  PipelineRoute: PipelineRoute,
  PwaIconsRoute: PwaIconsRoute,
  QrcodeRoute: QrcodeRoute,
  RandomPickerRoute: RandomPickerRoute,
  RealtimeDebuggerRoute: RealtimeDebuggerRoute,
  RecipeScaleRoute: RecipeScaleRoute,
  RegexRoute: RegexRoute,
  RmbUppercaseRoute: RmbUppercaseRoute,
  Rot13Route: Rot13Route,
  SalaryTaxRoute: SalaryTaxRoute,
  ScreenRecorderRoute: ScreenRecorderRoute,
  SeoFilesRoute: SeoFilesRoute,
  SettingsRoute: SettingsRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SizeConverterRoute: SizeConverterRoute,
  SocialInsuranceRoute: SocialInsuranceRoute,
  SqlRoute: SqlRoute,
  SqlDataRoute: SqlDataRoute,
  SqlPlaygroundRoute: SqlPlaygroundRoute,
  SubtitleEditorRoute: SubtitleEditorRoute,
  SvgToolkitRoute: SvgToolkitRoute,
  TableConvertRoute: TableConvertRoute,
  TemperatureRoute: TemperatureRoute,
  TextRoute: TextRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  TotpRoute: TotpRoute,
  TraceContextRoute: TraceContextRoute,
  TravelCostRoute: TravelCostRoute,
  UnicodeRoute: UnicodeRoute,
  UnitConverterRoute: UnitConverterRoute,
  UnixPermissionsRoute: UnixPermissionsRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UserAgentRoute: UserAgentRoute,
  UuidRoute: UuidRoute,
  VideoAnimationRoute: VideoAnimationRoute,
  VideoEditorRoute: VideoEditorRoute,
  VideoTrimmerRoute: VideoTrimmerRoute,
  WebauthnDebuggerRoute: WebauthnDebuggerRoute,
  WebpGifRoute: WebpGifRoute,
  WebrtcDiagnosticsRoute: WebrtcDiagnosticsRoute,
  WorldClockRoute: WorldClockRoute,
  XmlRoute: XmlRoute,
  XmlJsonRoute: XmlJsonRoute,
  YamlRoute: YamlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
