/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YamlRouteImport } from './routes/yaml'
import { Route as XmlJsonRouteImport } from './routes/xml-json'
import { Route as XmlRouteImport } from './routes/xml'
import { Route as WorldClockRouteImport } from './routes/world-clock'
import { Route as WebpGifRouteImport } from './routes/webp-gif'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UserAgentRouteImport } from './routes/user-agent'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as UnicodeRouteImport } from './routes/unicode'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as TextRouteImport } from './routes/text'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as TableConvertRouteImport } from './routes/table-convert'
import { Route as SqlPlaygroundRouteImport } from './routes/sql-playground'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as SocialInsuranceRouteImport } from './routes/social-insurance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenRecorderRouteImport } from './routes/screen-recorder'
import { Route as Rot13RouteImport } from './routes/rot13'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as NumberBaseRouteImport } from './routes/number-base'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MarkdownRouteImport } from './routes/markdown'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonRouteImport } from './routes/json'
import { Route as JsRouteImport } from './routes/js'
import { Route as IpLookupRouteImport } from './routes/ip-lookup'
import { Route as ImageRouteImport } from './routes/image'
import { Route as HttpStatusRouteImport } from './routes/http-status'
import { Route as HttpRequestRouteImport } from './routes/http-request'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as HmacRouteImport } from './routes/hmac'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GushiNamerRouteImport } from './routes/gushi-namer'
import { Route as FontRouteImport } from './routes/font'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DatetimeRouteImport } from './routes/datetime'
import { Route as CsvConvertRouteImport } from './routes/csv-convert'
import { Route as CssUnitRouteImport } from './routes/css-unit'
import { Route as CssLayoutRouteImport } from './routes/css-layout'
import { Route as CssAnimationRouteImport } from './routes/css-animation'
import { Route as CssRouteImport } from './routes/css'
import { Route as CorsRouteImport } from './routes/cors'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContrastRouteImport } from './routes/contrast'
import { Route as ColorConverterRouteImport } from './routes/color-converter'
import { Route as CipherRouteImport } from './routes/cipher'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as IndexRouteImport } from './routes/index'

const YamlRoute = YamlRouteImport.update({
  id: '/yaml',
  path: '/yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlJsonRoute = XmlJsonRouteImport.update({
  id: '/xml-json',
  path: '/xml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlRoute = XmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldClockRoute = WorldClockRouteImport.update({
  id: '/world-clock',
  path: '/world-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const WebpGifRoute = WebpGifRouteImport.update({
  id: '/webp-gif',
  path: '/webp-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgentRoute = UserAgentRouteImport.update({
  id: '/user-agent',
  path: '/user-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const UnicodeRoute = UnicodeRouteImport.update({
  id: '/unicode',
  path: '/unicode',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const TableConvertRoute = TableConvertRouteImport.update({
  id: '/table-convert',
  path: '/table-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlPlaygroundRoute = SqlPlaygroundRouteImport.update({
  id: '/sql-playground',
  path: '/sql-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialInsuranceRoute = SocialInsuranceRouteImport.update({
  id: '/social-insurance',
  path: '/social-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRecorderRoute = ScreenRecorderRouteImport.update({
  id: '/screen-recorder',
  path: '/screen-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const Rot13Route = Rot13RouteImport.update({
  id: '/rot13',
  path: '/rot13',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberBaseRoute = NumberBaseRouteImport.update({
  id: '/number-base',
  path: '/number-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownRoute = MarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const JsRoute = JsRouteImport.update({
  id: '/js',
  path: '/js',
  getParentRoute: () => rootRouteImport,
} as any)
const IpLookupRoute = IpLookupRouteImport.update({
  id: '/ip-lookup',
  path: '/ip-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpRequestRoute = HttpRequestRouteImport.update({
  id: '/http-request',
  path: '/http-request',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const HmacRoute = HmacRouteImport.update({
  id: '/hmac',
  path: '/hmac',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GushiNamerRoute = GushiNamerRouteImport.update({
  id: '/gushi-namer',
  path: '/gushi-namer',
  getParentRoute: () => rootRouteImport,
} as any)
const FontRoute = FontRouteImport.update({
  id: '/font',
  path: '/font',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DatetimeRoute = DatetimeRouteImport.update({
  id: '/datetime',
  path: '/datetime',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvConvertRoute = CsvConvertRouteImport.update({
  id: '/csv-convert',
  path: '/csv-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CssUnitRoute = CssUnitRouteImport.update({
  id: '/css-unit',
  path: '/css-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const CssLayoutRoute = CssLayoutRouteImport.update({
  id: '/css-layout',
  path: '/css-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CssAnimationRoute = CssAnimationRouteImport.update({
  id: '/css-animation',
  path: '/css-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const CssRoute = CssRouteImport.update({
  id: '/css',
  path: '/css',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsRoute = CorsRouteImport.update({
  id: '/cors',
  path: '/cors',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrastRoute = ContrastRouteImport.update({
  id: '/contrast',
  path: '/contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorConverterRoute = ColorConverterRouteImport.update({
  id: '/color-converter',
  path: '/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CipherRoute = CipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/bmi': typeof BmiRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/font': typeof FontRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/image': typeof ImageRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/screen-recorder': typeof ScreenRecorderRoute
  '/settings': typeof SettingsRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/totp': typeof TotpRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/webp-gif': typeof WebpGifRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/bmi': typeof BmiRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/font': typeof FontRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/image': typeof ImageRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/screen-recorder': typeof ScreenRecorderRoute
  '/settings': typeof SettingsRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/totp': typeof TotpRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/webp-gif': typeof WebpGifRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/bmi': typeof BmiRoute
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/contrast': typeof ContrastRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/diff': typeof DiffRoute
  '/font': typeof FontRoute
  '/gushi-namer': typeof GushiNamerRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/image': typeof ImageRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/mortgage': typeof MortgageRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/screen-recorder': typeof ScreenRecorderRoute
  '/settings': typeof SettingsRoute
  '/social-insurance': typeof SocialInsuranceRoute
  '/sql': typeof SqlRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/table-convert': typeof TableConvertRoute
  '/temperature': typeof TemperatureRoute
  '/text': typeof TextRoute
  '/totp': typeof TotpRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/webp-gif': typeof WebpGifRoute
  '/world-clock': typeof WorldClockRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base64'
    | '/bmi'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-unit'
    | '/csv-convert'
    | '/datetime'
    | '/diff'
    | '/font'
    | '/gushi-namer'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/image'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mortgage'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/screen-recorder'
    | '/settings'
    | '/social-insurance'
    | '/sql'
    | '/sql-playground'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/totp'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/webp-gif'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base64'
    | '/bmi'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-unit'
    | '/csv-convert'
    | '/datetime'
    | '/diff'
    | '/font'
    | '/gushi-namer'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/image'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mortgage'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/screen-recorder'
    | '/settings'
    | '/social-insurance'
    | '/sql'
    | '/sql-playground'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/totp'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/webp-gif'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  id:
    | '__root__'
    | '/'
    | '/base64'
    | '/bmi'
    | '/cipher'
    | '/color-converter'
    | '/contrast'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/css-unit'
    | '/csv-convert'
    | '/datetime'
    | '/diff'
    | '/font'
    | '/gushi-namer'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/image'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/login'
    | '/markdown'
    | '/mortgage'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/screen-recorder'
    | '/settings'
    | '/social-insurance'
    | '/sql'
    | '/sql-playground'
    | '/table-convert'
    | '/temperature'
    | '/text'
    | '/totp'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/webp-gif'
    | '/world-clock'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Base64Route: typeof Base64Route
  BmiRoute: typeof BmiRoute
  CipherRoute: typeof CipherRoute
  ColorConverterRoute: typeof ColorConverterRoute
  ContrastRoute: typeof ContrastRoute
  CookieRoute: typeof CookieRoute
  CorsRoute: typeof CorsRoute
  CssRoute: typeof CssRoute
  CssAnimationRoute: typeof CssAnimationRoute
  CssLayoutRoute: typeof CssLayoutRoute
  CssUnitRoute: typeof CssUnitRoute
  CsvConvertRoute: typeof CsvConvertRoute
  DatetimeRoute: typeof DatetimeRoute
  DiffRoute: typeof DiffRoute
  FontRoute: typeof FontRoute
  GushiNamerRoute: typeof GushiNamerRoute
  HashRoute: typeof HashRoute
  HmacRoute: typeof HmacRoute
  HtmlRoute: typeof HtmlRoute
  HttpRequestRoute: typeof HttpRequestRoute
  HttpStatusRoute: typeof HttpStatusRoute
  ImageRoute: typeof ImageRoute
  IpLookupRoute: typeof IpLookupRoute
  JsRoute: typeof JsRoute
  JsonRoute: typeof JsonRoute
  JwtRoute: typeof JwtRoute
  LoginRoute: typeof LoginRoute
  MarkdownRoute: typeof MarkdownRoute
  MortgageRoute: typeof MortgageRoute
  NumberBaseRoute: typeof NumberBaseRoute
  PasswordRoute: typeof PasswordRoute
  QrcodeRoute: typeof QrcodeRoute
  RegexRoute: typeof RegexRoute
  Rot13Route: typeof Rot13Route
  ScreenRecorderRoute: typeof ScreenRecorderRoute
  SettingsRoute: typeof SettingsRoute
  SocialInsuranceRoute: typeof SocialInsuranceRoute
  SqlRoute: typeof SqlRoute
  SqlPlaygroundRoute: typeof SqlPlaygroundRoute
  TableConvertRoute: typeof TableConvertRoute
  TemperatureRoute: typeof TemperatureRoute
  TextRoute: typeof TextRoute
  TotpRoute: typeof TotpRoute
  UnicodeRoute: typeof UnicodeRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UserAgentRoute: typeof UserAgentRoute
  UuidRoute: typeof UuidRoute
  WebpGifRoute: typeof WebpGifRoute
  WorldClockRoute: typeof WorldClockRoute
  XmlRoute: typeof XmlRoute
  XmlJsonRoute: typeof XmlJsonRoute
  YamlRoute: typeof YamlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaml': {
      id: '/yaml'
      path: '/yaml'
      fullPath: '/yaml'
      preLoaderRoute: typeof YamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-json': {
      id: '/xml-json'
      path: '/xml-json'
      fullPath: '/xml-json'
      preLoaderRoute: typeof XmlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml': {
      id: '/xml'
      path: '/xml'
      fullPath: '/xml'
      preLoaderRoute: typeof XmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-clock': {
      id: '/world-clock'
      path: '/world-clock'
      fullPath: '/world-clock'
      preLoaderRoute: typeof WorldClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webp-gif': {
      id: '/webp-gif'
      path: '/webp-gif'
      fullPath: '/webp-gif'
      preLoaderRoute: typeof WebpGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agent': {
      id: '/user-agent'
      path: '/user-agent'
      fullPath: '/user-agent'
      preLoaderRoute: typeof UserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unicode': {
      id: '/unicode'
      path: '/unicode'
      fullPath: '/unicode'
      preLoaderRoute: typeof UnicodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-convert': {
      id: '/table-convert'
      path: '/table-convert'
      fullPath: '/table-convert'
      preLoaderRoute: typeof TableConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-playground': {
      id: '/sql-playground'
      path: '/sql-playground'
      fullPath: '/sql-playground'
      preLoaderRoute: typeof SqlPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-insurance': {
      id: '/social-insurance'
      path: '/social-insurance'
      fullPath: '/social-insurance'
      preLoaderRoute: typeof SocialInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-recorder': {
      id: '/screen-recorder'
      path: '/screen-recorder'
      fullPath: '/screen-recorder'
      preLoaderRoute: typeof ScreenRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rot13': {
      id: '/rot13'
      path: '/rot13'
      fullPath: '/rot13'
      preLoaderRoute: typeof Rot13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-base': {
      id: '/number-base'
      path: '/number-base'
      fullPath: '/number-base'
      preLoaderRoute: typeof NumberBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js': {
      id: '/js'
      path: '/js'
      fullPath: '/js'
      preLoaderRoute: typeof JsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-lookup': {
      id: '/ip-lookup'
      path: '/ip-lookup'
      fullPath: '/ip-lookup'
      preLoaderRoute: typeof IpLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-status': {
      id: '/http-status'
      path: '/http-status'
      fullPath: '/http-status'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-request': {
      id: '/http-request'
      path: '/http-request'
      fullPath: '/http-request'
      preLoaderRoute: typeof HttpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmac': {
      id: '/hmac'
      path: '/hmac'
      fullPath: '/hmac'
      preLoaderRoute: typeof HmacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gushi-namer': {
      id: '/gushi-namer'
      path: '/gushi-namer'
      fullPath: '/gushi-namer'
      preLoaderRoute: typeof GushiNamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font': {
      id: '/font'
      path: '/font'
      fullPath: '/font'
      preLoaderRoute: typeof FontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datetime': {
      id: '/datetime'
      path: '/datetime'
      fullPath: '/datetime'
      preLoaderRoute: typeof DatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-convert': {
      id: '/csv-convert'
      path: '/csv-convert'
      fullPath: '/csv-convert'
      preLoaderRoute: typeof CsvConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-unit': {
      id: '/css-unit'
      path: '/css-unit'
      fullPath: '/css-unit'
      preLoaderRoute: typeof CssUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-layout': {
      id: '/css-layout'
      path: '/css-layout'
      fullPath: '/css-layout'
      preLoaderRoute: typeof CssLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-animation': {
      id: '/css-animation'
      path: '/css-animation'
      fullPath: '/css-animation'
      preLoaderRoute: typeof CssAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css': {
      id: '/css'
      path: '/css'
      fullPath: '/css'
      preLoaderRoute: typeof CssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cors': {
      id: '/cors'
      path: '/cors'
      fullPath: '/cors'
      preLoaderRoute: typeof CorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrast': {
      id: '/contrast'
      path: '/contrast'
      fullPath: '/contrast'
      preLoaderRoute: typeof ContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-converter': {
      id: '/color-converter'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof ColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cipher': {
      id: '/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof CipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64Route: Base64Route,
  BmiRoute: BmiRoute,
  CipherRoute: CipherRoute,
  ColorConverterRoute: ColorConverterRoute,
  ContrastRoute: ContrastRoute,
  CookieRoute: CookieRoute,
  CorsRoute: CorsRoute,
  CssRoute: CssRoute,
  CssAnimationRoute: CssAnimationRoute,
  CssLayoutRoute: CssLayoutRoute,
  CssUnitRoute: CssUnitRoute,
  CsvConvertRoute: CsvConvertRoute,
  DatetimeRoute: DatetimeRoute,
  DiffRoute: DiffRoute,
  FontRoute: FontRoute,
  GushiNamerRoute: GushiNamerRoute,
  HashRoute: HashRoute,
  HmacRoute: HmacRoute,
  HtmlRoute: HtmlRoute,
  HttpRequestRoute: HttpRequestRoute,
  HttpStatusRoute: HttpStatusRoute,
  ImageRoute: ImageRoute,
  IpLookupRoute: IpLookupRoute,
  JsRoute: JsRoute,
  JsonRoute: JsonRoute,
  JwtRoute: JwtRoute,
  LoginRoute: LoginRoute,
  MarkdownRoute: MarkdownRoute,
  MortgageRoute: MortgageRoute,
  NumberBaseRoute: NumberBaseRoute,
  PasswordRoute: PasswordRoute,
  QrcodeRoute: QrcodeRoute,
  RegexRoute: RegexRoute,
  Rot13Route: Rot13Route,
  ScreenRecorderRoute: ScreenRecorderRoute,
  SettingsRoute: SettingsRoute,
  SocialInsuranceRoute: SocialInsuranceRoute,
  SqlRoute: SqlRoute,
  SqlPlaygroundRoute: SqlPlaygroundRoute,
  TableConvertRoute: TableConvertRoute,
  TemperatureRoute: TemperatureRoute,
  TextRoute: TextRoute,
  TotpRoute: TotpRoute,
  UnicodeRoute: UnicodeRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UserAgentRoute: UserAgentRoute,
  UuidRoute: UuidRoute,
  WebpGifRoute: WebpGifRoute,
  WorldClockRoute: WorldClockRoute,
  XmlRoute: XmlRoute,
  XmlJsonRoute: XmlJsonRoute,
  YamlRoute: YamlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
