import { useTranslation } from 'react-i18next';
export const SECURITY_ZH = {
  encrypt: '加密',
  decrypt: '解密',
  sign: '签名',
  verify: '验签',
  inspect: '查看公钥',
  run: '处理',
  clear: '清空',
  running: '处理中…',
  failed: '处理失败：{{msg}}',
  key: '密钥',
  secretKey: '私钥 / 对称密钥',
  publicKey: '公钥',
  passphrase: '私钥密码',
  password: '证书包密码',
  generate: '生成密钥',
  input: '输入',
  output: '结果',
  footer: 'Footer（可选）',
  assertion: '隐式断言（可选）',
  jweKey: '密钥（64 位十六进制）',
  jweLimit: 'dir / A256GCM',
  pasetoLimit:
    '生成令牌默认添加 iat 和一小时有效期 exp；验签 / 解密同时校验时间声明。',
  importFile: '选择文件',
  download: '下载结果',
  signature: '分离签名（ASCII Armor）',
  pgpTitle: 'OpenPGP',
  pgpKey: '密钥（ASCII Armor）',
  pgpLimit: '文件上限 20 MB；签名与验签使用分离签名。',
  fileSelected: '已选择：{{name}}',
  useText: '改用文本',
  pfxLimit: '支持 PFX / P12，文件上限 10 MB。',
  certificateCount: '证书 {{count}} 张，私钥条目 {{keys}} 个',
  exportPem: '导出全部证书 PEM',
  subject: '主题',
  issuer: '签发者',
  validity: '有效期',
  serial: '序列号',
  dmarc: 'DMARC 聚合报告',
  dmarcLimit: '导入 XML / GZ；解压后上限 20 MB。',
  example: '示例',
  total: '邮件总数',
  aligned: 'DMARC 对齐通过',
  organization: '报告组织',
  domain: '域名',
  sourceIp: '来源 IP',
  count: '邮件量',
  spfPass: 'SPF 对齐通过',
  dkimPass: 'DKIM 对齐通过',
  noFile: '请先选择文件',
  verified: '签名验证通过',
  verificationNote: '仅验证数据与提供公钥匹配，不确认公钥持有者身份。',
  pfxNote: '展示包内证书及签发关系；未验证系统信任或吊销状态。',
} as const;
export const SECURITY_EN: Record<keyof typeof SECURITY_ZH, string> = {
  encrypt: 'Encrypt',
  decrypt: 'Decrypt',
  sign: 'Sign',
  verify: 'Verify',
  inspect: 'Inspect public key',
  run: 'Run',
  clear: 'Clear',
  running: 'Processing…',
  failed: 'Processing failed: {{msg}}',
  key: 'Key',
  secretKey: 'Private / symmetric key',
  publicKey: 'Public key',
  passphrase: 'Private key passphrase',
  password: 'Bundle password',
  generate: 'Generate key',
  input: 'Input',
  output: 'Result',
  footer: 'Footer (optional)',
  assertion: 'Implicit assertion (optional)',
  jweKey: 'Key (64 hexadecimal digits)',
  jweLimit: 'dir / A256GCM',
  pasetoLimit:
    'Generated tokens add iat and a one-hour exp by default; verification and decryption also validate time claims.',
  importFile: 'Choose file',
  download: 'Download result',
  signature: 'Detached signature (ASCII Armor)',
  pgpTitle: 'OpenPGP',
  pgpKey: 'Key (ASCII Armor)',
  pgpLimit:
    'Maximum file size: 20 MB. Signing and verification use detached signatures.',
  fileSelected: 'Selected: {{name}}',
  useText: 'Use text instead',
  pfxLimit: 'PFX / P12, maximum 10 MB.',
  certificateCount: '{{count}} certificates, {{keys}} private key entries',
  exportPem: 'Export all certificates as PEM',
  subject: 'Subject',
  issuer: 'Issuer',
  validity: 'Validity',
  serial: 'Serial number',
  dmarc: 'DMARC aggregate report',
  dmarcLimit: 'Import XML / GZ; maximum decompressed size: 20 MB.',
  example: 'Example',
  total: 'Total messages',
  aligned: 'DMARC aligned',
  organization: 'Reporting organization',
  domain: 'Domain',
  sourceIp: 'Source IP',
  count: 'Messages',
  spfPass: 'SPF aligned',
  dkimPass: 'DKIM aligned',
  noFile: 'Choose a file first',
  verified: 'Signature verified',
  verificationNote:
    'Verification confirms the data matches the provided key, not the key owner’s identity.',
  pfxNote:
    'Shows bundled certificates and issuer relationships; system trust and revocation are not checked.',
};
export function useSecurityText() {
  const { t } = useTranslation();
  return (
    key: keyof typeof SECURITY_ZH,
    values?: Record<string, string | number>,
  ) =>
    t(`securityWorkbench.${key}`, {
      defaultValue: SECURITY_ZH[key],
      ...values,
    });
}
