/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YamlRouteImport } from './routes/yaml'
import { Route as XmlJsonRouteImport } from './routes/xml-json'
import { Route as XmlRouteImport } from './routes/xml'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UserAgentRouteImport } from './routes/user-agent'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as UnicodeRouteImport } from './routes/unicode'
import { Route as TextRouteImport } from './routes/text'
import { Route as TableConvertRouteImport } from './routes/table-convert'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as Rot13RouteImport } from './routes/rot13'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as NumberBaseRouteImport } from './routes/number-base'
import { Route as MarkdownRouteImport } from './routes/markdown'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonRouteImport } from './routes/json'
import { Route as JsRouteImport } from './routes/js'
import { Route as IpLookupRouteImport } from './routes/ip-lookup'
import { Route as HttpStatusRouteImport } from './routes/http-status'
import { Route as HttpRequestRouteImport } from './routes/http-request'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as HmacRouteImport } from './routes/hmac'
import { Route as HashRouteImport } from './routes/hash'
import { Route as DatetimeRouteImport } from './routes/datetime'
import { Route as CsvConvertRouteImport } from './routes/csv-convert'
import { Route as CssLayoutRouteImport } from './routes/css-layout'
import { Route as CssAnimationRouteImport } from './routes/css-animation'
import { Route as CssRouteImport } from './routes/css'
import { Route as CorsRouteImport } from './routes/cors'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ColorConverterRouteImport } from './routes/color-converter'
import { Route as CipherRouteImport } from './routes/cipher'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as IndexRouteImport } from './routes/index'

const YamlRoute = YamlRouteImport.update({
  id: '/yaml',
  path: '/yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlJsonRoute = XmlJsonRouteImport.update({
  id: '/xml-json',
  path: '/xml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlRoute = XmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgentRoute = UserAgentRouteImport.update({
  id: '/user-agent',
  path: '/user-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const UnicodeRoute = UnicodeRouteImport.update({
  id: '/unicode',
  path: '/unicode',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const TableConvertRoute = TableConvertRouteImport.update({
  id: '/table-convert',
  path: '/table-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const Rot13Route = Rot13RouteImport.update({
  id: '/rot13',
  path: '/rot13',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberBaseRoute = NumberBaseRouteImport.update({
  id: '/number-base',
  path: '/number-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownRoute = MarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const JsRoute = JsRouteImport.update({
  id: '/js',
  path: '/js',
  getParentRoute: () => rootRouteImport,
} as any)
const IpLookupRoute = IpLookupRouteImport.update({
  id: '/ip-lookup',
  path: '/ip-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpRequestRoute = HttpRequestRouteImport.update({
  id: '/http-request',
  path: '/http-request',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const HmacRoute = HmacRouteImport.update({
  id: '/hmac',
  path: '/hmac',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const DatetimeRoute = DatetimeRouteImport.update({
  id: '/datetime',
  path: '/datetime',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvConvertRoute = CsvConvertRouteImport.update({
  id: '/csv-convert',
  path: '/csv-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CssLayoutRoute = CssLayoutRouteImport.update({
  id: '/css-layout',
  path: '/css-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CssAnimationRoute = CssAnimationRouteImport.update({
  id: '/css-animation',
  path: '/css-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const CssRoute = CssRouteImport.update({
  id: '/css',
  path: '/css',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsRoute = CorsRouteImport.update({
  id: '/cors',
  path: '/cors',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorConverterRoute = ColorConverterRouteImport.update({
  id: '/color-converter',
  path: '/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CipherRoute = CipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/markdown': typeof MarkdownRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/sql': typeof SqlRoute
  '/table-convert': typeof TableConvertRoute
  '/text': typeof TextRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/markdown': typeof MarkdownRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/sql': typeof SqlRoute
  '/table-convert': typeof TableConvertRoute
  '/text': typeof TextRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/cipher': typeof CipherRoute
  '/color-converter': typeof ColorConverterRoute
  '/cookie': typeof CookieRoute
  '/cors': typeof CorsRoute
  '/css': typeof CssRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-layout': typeof CssLayoutRoute
  '/csv-convert': typeof CsvConvertRoute
  '/datetime': typeof DatetimeRoute
  '/hash': typeof HashRoute
  '/hmac': typeof HmacRoute
  '/html': typeof HtmlRoute
  '/http-request': typeof HttpRequestRoute
  '/http-status': typeof HttpStatusRoute
  '/ip-lookup': typeof IpLookupRoute
  '/js': typeof JsRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/markdown': typeof MarkdownRoute
  '/number-base': typeof NumberBaseRoute
  '/password': typeof PasswordRoute
  '/qrcode': typeof QrcodeRoute
  '/regex': typeof RegexRoute
  '/rot13': typeof Rot13Route
  '/sql': typeof SqlRoute
  '/table-convert': typeof TableConvertRoute
  '/text': typeof TextRoute
  '/unicode': typeof UnicodeRoute
  '/url-encode': typeof UrlEncodeRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/xml-json': typeof XmlJsonRoute
  '/yaml': typeof YamlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base64'
    | '/cipher'
    | '/color-converter'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/csv-convert'
    | '/datetime'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/markdown'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/sql'
    | '/table-convert'
    | '/text'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base64'
    | '/cipher'
    | '/color-converter'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/csv-convert'
    | '/datetime'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/markdown'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/sql'
    | '/table-convert'
    | '/text'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  id:
    | '__root__'
    | '/'
    | '/base64'
    | '/cipher'
    | '/color-converter'
    | '/cookie'
    | '/cors'
    | '/css'
    | '/css-animation'
    | '/css-layout'
    | '/csv-convert'
    | '/datetime'
    | '/hash'
    | '/hmac'
    | '/html'
    | '/http-request'
    | '/http-status'
    | '/ip-lookup'
    | '/js'
    | '/json'
    | '/jwt'
    | '/markdown'
    | '/number-base'
    | '/password'
    | '/qrcode'
    | '/regex'
    | '/rot13'
    | '/sql'
    | '/table-convert'
    | '/text'
    | '/unicode'
    | '/url-encode'
    | '/user-agent'
    | '/uuid'
    | '/xml'
    | '/xml-json'
    | '/yaml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Base64Route: typeof Base64Route
  CipherRoute: typeof CipherRoute
  ColorConverterRoute: typeof ColorConverterRoute
  CookieRoute: typeof CookieRoute
  CorsRoute: typeof CorsRoute
  CssRoute: typeof CssRoute
  CssAnimationRoute: typeof CssAnimationRoute
  CssLayoutRoute: typeof CssLayoutRoute
  CsvConvertRoute: typeof CsvConvertRoute
  DatetimeRoute: typeof DatetimeRoute
  HashRoute: typeof HashRoute
  HmacRoute: typeof HmacRoute
  HtmlRoute: typeof HtmlRoute
  HttpRequestRoute: typeof HttpRequestRoute
  HttpStatusRoute: typeof HttpStatusRoute
  IpLookupRoute: typeof IpLookupRoute
  JsRoute: typeof JsRoute
  JsonRoute: typeof JsonRoute
  JwtRoute: typeof JwtRoute
  MarkdownRoute: typeof MarkdownRoute
  NumberBaseRoute: typeof NumberBaseRoute
  PasswordRoute: typeof PasswordRoute
  QrcodeRoute: typeof QrcodeRoute
  RegexRoute: typeof RegexRoute
  Rot13Route: typeof Rot13Route
  SqlRoute: typeof SqlRoute
  TableConvertRoute: typeof TableConvertRoute
  TextRoute: typeof TextRoute
  UnicodeRoute: typeof UnicodeRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UserAgentRoute: typeof UserAgentRoute
  UuidRoute: typeof UuidRoute
  XmlRoute: typeof XmlRoute
  XmlJsonRoute: typeof XmlJsonRoute
  YamlRoute: typeof YamlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaml': {
      id: '/yaml'
      path: '/yaml'
      fullPath: '/yaml'
      preLoaderRoute: typeof YamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-json': {
      id: '/xml-json'
      path: '/xml-json'
      fullPath: '/xml-json'
      preLoaderRoute: typeof XmlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml': {
      id: '/xml'
      path: '/xml'
      fullPath: '/xml'
      preLoaderRoute: typeof XmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agent': {
      id: '/user-agent'
      path: '/user-agent'
      fullPath: '/user-agent'
      preLoaderRoute: typeof UserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unicode': {
      id: '/unicode'
      path: '/unicode'
      fullPath: '/unicode'
      preLoaderRoute: typeof UnicodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-convert': {
      id: '/table-convert'
      path: '/table-convert'
      fullPath: '/table-convert'
      preLoaderRoute: typeof TableConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rot13': {
      id: '/rot13'
      path: '/rot13'
      fullPath: '/rot13'
      preLoaderRoute: typeof Rot13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-base': {
      id: '/number-base'
      path: '/number-base'
      fullPath: '/number-base'
      preLoaderRoute: typeof NumberBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js': {
      id: '/js'
      path: '/js'
      fullPath: '/js'
      preLoaderRoute: typeof JsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-lookup': {
      id: '/ip-lookup'
      path: '/ip-lookup'
      fullPath: '/ip-lookup'
      preLoaderRoute: typeof IpLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-status': {
      id: '/http-status'
      path: '/http-status'
      fullPath: '/http-status'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-request': {
      id: '/http-request'
      path: '/http-request'
      fullPath: '/http-request'
      preLoaderRoute: typeof HttpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmac': {
      id: '/hmac'
      path: '/hmac'
      fullPath: '/hmac'
      preLoaderRoute: typeof HmacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datetime': {
      id: '/datetime'
      path: '/datetime'
      fullPath: '/datetime'
      preLoaderRoute: typeof DatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-convert': {
      id: '/csv-convert'
      path: '/csv-convert'
      fullPath: '/csv-convert'
      preLoaderRoute: typeof CsvConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-layout': {
      id: '/css-layout'
      path: '/css-layout'
      fullPath: '/css-layout'
      preLoaderRoute: typeof CssLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-animation': {
      id: '/css-animation'
      path: '/css-animation'
      fullPath: '/css-animation'
      preLoaderRoute: typeof CssAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css': {
      id: '/css'
      path: '/css'
      fullPath: '/css'
      preLoaderRoute: typeof CssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cors': {
      id: '/cors'
      path: '/cors'
      fullPath: '/cors'
      preLoaderRoute: typeof CorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-converter': {
      id: '/color-converter'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof ColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cipher': {
      id: '/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof CipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64Route: Base64Route,
  CipherRoute: CipherRoute,
  ColorConverterRoute: ColorConverterRoute,
  CookieRoute: CookieRoute,
  CorsRoute: CorsRoute,
  CssRoute: CssRoute,
  CssAnimationRoute: CssAnimationRoute,
  CssLayoutRoute: CssLayoutRoute,
  CsvConvertRoute: CsvConvertRoute,
  DatetimeRoute: DatetimeRoute,
  HashRoute: HashRoute,
  HmacRoute: HmacRoute,
  HtmlRoute: HtmlRoute,
  HttpRequestRoute: HttpRequestRoute,
  HttpStatusRoute: HttpStatusRoute,
  IpLookupRoute: IpLookupRoute,
  JsRoute: JsRoute,
  JsonRoute: JsonRoute,
  JwtRoute: JwtRoute,
  MarkdownRoute: MarkdownRoute,
  NumberBaseRoute: NumberBaseRoute,
  PasswordRoute: PasswordRoute,
  QrcodeRoute: QrcodeRoute,
  RegexRoute: RegexRoute,
  Rot13Route: Rot13Route,
  SqlRoute: SqlRoute,
  TableConvertRoute: TableConvertRoute,
  TextRoute: TextRoute,
  UnicodeRoute: UnicodeRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UserAgentRoute: UserAgentRoute,
  UuidRoute: UuidRoute,
  XmlRoute: XmlRoute,
  XmlJsonRoute: XmlJsonRoute,
  YamlRoute: YamlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
