import {
  ChartNoAxesCombined,
  KanbanSquare,
  ClipboardList,
  ReceiptText,
  Quote,
  ContactRound,
  Bookmark,
  Workflow,
  Route,
  PackageOpen,
} from 'lucide-react';
export const BATCH3_TOOLS = [
  {
    id: 'data-charts',
    icon: ChartNoAxesCombined,
    color: 'text-blue-500',
    key: 'analysis3.charts',
    keywords: '数据 透视 柱状 折线 散点 饼图 CSV JSON chart pivot',
  },
  {
    id: 'project-planner',
    icon: KanbanSquare,
    color: 'text-emerald-500',
    key: 'productivity.tools.project-planner',
    keywords: '项目 看板 甘特 里程碑 依赖 project kanban gantt',
  },
  {
    id: 'form-builder',
    icon: ClipboardList,
    color: 'text-violet-500',
    key: 'productivity.tools.form-builder',
    keywords: '表单 字段 条件 问卷 form survey',
  },
  {
    id: 'document-maker',
    icon: ReceiptText,
    color: 'text-amber-500',
    key: 'productivity.tools.document-maker',
    keywords: '报价 收据 装箱 单据 quote receipt packing',
  },
  {
    id: 'citation-tool',
    icon: Quote,
    color: 'text-rose-500',
    key: 'analysis3.citations',
    keywords: '文献 引用 参考 BibTeX RIS CSL citation bibliography',
  },
  {
    id: 'contacts-tool',
    icon: ContactRound,
    color: 'text-cyan-500',
    key: 'productivity.tools.contacts-tool',
    keywords: '联系人 名片 VCF vCard CSV contacts',
  },
  {
    id: 'bookmark-manager',
    icon: Bookmark,
    color: 'text-orange-500',
    key: 'productivity.tools.bookmark-manager',
    keywords: '书签 目录 链接 去重 bookmark browser HTML',
  },
  {
    id: 'logic-workbench',
    icon: Workflow,
    color: 'text-fuchsia-500',
    key: 'analysis3.logic',
    keywords: '逻辑 真值表 布尔 卡诺 等价 boolean karnaugh logic',
  },
  {
    id: 'algorithm-lab',
    icon: Route,
    color: 'text-lime-500',
    key: 'analysis3.algorithms',
    keywords: '算法 排序 二分 寻路 BFS Dijkstra algorithm sort',
  },
  {
    id: 'packaging-designer',
    icon: PackageOpen,
    color: 'text-teal-500',
    key: 'analysis3.packaging',
    keywords: '包装 纸盒 信封 纸袋 裁切 折叠 packaging box envelope',
  },
] as const;
