// Sources: https://ciaaw.org/abridged-atomic-weights.htm (2024 abridged weights); https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON (symbols and configurations). Retrieved 2026-09-23.
export const ELEMENTS: Array<{
  number: number;
  symbol: string;
  name: string;
  zh: string;
  mass: number | null;
  configuration: string;
}> = [
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    zh: '氢',
    mass: 1.008,
    configuration: '1s1',
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    zh: '氦',
    mass: 4.0026,
    configuration: '1s2',
  },
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    zh: '锂',
    mass: 6.94,
    configuration: '[He]2s1',
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    zh: '铍',
    mass: 9.0122,
    configuration: '[He]2s2',
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    zh: '硼',
    mass: 10.81,
    configuration: '[He]2s2 2p1',
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    zh: '碳',
    mass: 12.011,
    configuration: '[He]2s2 2p2',
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    zh: '氮',
    mass: 14.007,
    configuration: '[He] 2s2 2p3',
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    zh: '氧',
    mass: 15.999,
    configuration: '[He]2s2 2p4',
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    zh: '氟',
    mass: 18.998,
    configuration: '[He]2s2 2p5',
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    zh: '氖',
    mass: 20.18,
    configuration: '[He]2s2 2p6',
  },
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    zh: '钠',
    mass: 22.99,
    configuration: '[Ne]3s1',
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    zh: '镁',
    mass: 24.305,
    configuration: '[Ne]3s2',
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminum',
    zh: '铝',
    mass: 26.982,
    configuration: '[Ne]3s2 3p1',
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    zh: '硅',
    mass: 28.085,
    configuration: '[Ne]3s2 3p2',
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    zh: '磷',
    mass: 30.974,
    configuration: '[Ne]3s2 3p3',
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    zh: '硫',
    mass: 32.06,
    configuration: '[Ne]3s2 3p4',
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    zh: '氯',
    mass: 35.45,
    configuration: '[Ne]3s2 3p5',
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    zh: '氩',
    mass: 39.95,
    configuration: '[Ne]3s2 3p6',
  },
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    zh: '钾',
    mass: 39.098,
    configuration: '[Ar]4s1',
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    zh: '钙',
    mass: 40.078,
    configuration: '[Ar]4s2',
  },
  {
    number: 21,
    symbol: 'Sc',
    name: 'Scandium',
    zh: '钪',
    mass: 44.956,
    configuration: '[Ar]4s2 3d1',
  },
  {
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    zh: '钛',
    mass: 47.867,
    configuration: '[Ar]4s2 3d2',
  },
  {
    number: 23,
    symbol: 'V',
    name: 'Vanadium',
    zh: '钒',
    mass: 50.942,
    configuration: '[Ar]4s2 3d3',
  },
  {
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    zh: '铬',
    mass: 51.996,
    configuration: '[Ar]3d5 4s1',
  },
  {
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    zh: '锰',
    mass: 54.938,
    configuration: '[Ar]4s2 3d5',
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    zh: '铁',
    mass: 55.845,
    configuration: '[Ar]4s2 3d6',
  },
  {
    number: 27,
    symbol: 'Co',
    name: 'Cobalt',
    zh: '钴',
    mass: 58.933,
    configuration: '[Ar]4s2 3d7',
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    zh: '镍',
    mass: 58.693,
    configuration: '[Ar]4s2 3d8',
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    zh: '铜',
    mass: 63.546,
    configuration: '[Ar]4s1 3d10',
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    zh: '锌',
    mass: 65.38,
    configuration: '[Ar]4s2 3d10',
  },
  {
    number: 31,
    symbol: 'Ga',
    name: 'Gallium',
    zh: '镓',
    mass: 69.723,
    configuration: '[Ar]4s2 3d10 4p1',
  },
  {
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    zh: '锗',
    mass: 72.63,
    configuration: '[Ar]4s2 3d10 4p2',
  },
  {
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    zh: '砷',
    mass: 74.922,
    configuration: '[Ar]4s2 3d10 4p3',
  },
  {
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    zh: '硒',
    mass: 78.971,
    configuration: '[Ar]4s2 3d10 4p4',
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    zh: '溴',
    mass: 79.904,
    configuration: '[Ar]4s2 3d10 4p5',
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    zh: '氪',
    mass: 83.798,
    configuration: '[Ar]4s2 3d10 4p6',
  },
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    zh: '铷',
    mass: 85.468,
    configuration: '[Kr]5s1',
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    zh: '锶',
    mass: 87.62,
    configuration: '[Kr]5s2',
  },
  {
    number: 39,
    symbol: 'Y',
    name: 'Yttrium',
    zh: '钇',
    mass: 88.906,
    configuration: '[Kr]5s2 4d1',
  },
  {
    number: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    zh: '锆',
    mass: 91.222,
    configuration: '[Kr]5s2 4d2',
  },
  {
    number: 41,
    symbol: 'Nb',
    name: 'Niobium',
    zh: '铌',
    mass: 92.906,
    configuration: '[Kr]5s1 4d4',
  },
  {
    number: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    zh: '钼',
    mass: 95.95,
    configuration: '[Kr]5s1 4d5',
  },
  {
    number: 43,
    symbol: 'Tc',
    name: 'Technetium',
    zh: '锝',
    mass: null,
    configuration: '[Kr]5s2 4d5',
  },
  {
    number: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    zh: '钌',
    mass: 101.07,
    configuration: '[Kr]5s1 4d7',
  },
  {
    number: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    zh: '铑',
    mass: 102.91,
    configuration: '[Kr]5s1 4d8',
  },
  {
    number: 46,
    symbol: 'Pd',
    name: 'Palladium',
    zh: '钯',
    mass: 106.42,
    configuration: '[Kr]4d10',
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    zh: '银',
    mass: 107.87,
    configuration: '[Kr]5s1 4d10',
  },
  {
    number: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    zh: '镉',
    mass: 112.41,
    configuration: '[Kr]5s2 4d10',
  },
  {
    number: 49,
    symbol: 'In',
    name: 'Indium',
    zh: '铟',
    mass: 114.82,
    configuration: '[Kr]5s2 4d10 5p1',
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    zh: '锡',
    mass: 118.71,
    configuration: '[Kr]5s2 4d10 5p2',
  },
  {
    number: 51,
    symbol: 'Sb',
    name: 'Antimony',
    zh: '锑',
    mass: 121.76,
    configuration: '[Kr]5s2 4d10 5p3',
  },
  {
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    zh: '碲',
    mass: 127.6,
    configuration: '[Kr]5s2 4d10 5p4',
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    zh: '碘',
    mass: 126.9,
    configuration: '[Kr]5s2 4d10 5p5',
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    zh: '氙',
    mass: 131.29,
    configuration: '[Kr]5s2 4d10 5p6',
  },
  {
    number: 55,
    symbol: 'Cs',
    name: 'Cesium',
    zh: '铯',
    mass: 132.91,
    configuration: '[Xe]6s1',
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    zh: '钡',
    mass: 137.33,
    configuration: '[Xe]6s2',
  },
  {
    number: 57,
    symbol: 'La',
    name: 'Lanthanum',
    zh: '镧',
    mass: 138.91,
    configuration: '[Xe]6s2 5d1',
  },
  {
    number: 58,
    symbol: 'Ce',
    name: 'Cerium',
    zh: '铈',
    mass: 140.12,
    configuration: '[Xe]6s2 4f1 5d1',
  },
  {
    number: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    zh: '镨',
    mass: 140.91,
    configuration: '[Xe]6s2 4f3',
  },
  {
    number: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    zh: '钕',
    mass: 144.24,
    configuration: '[Xe]6s2 4f4',
  },
  {
    number: 61,
    symbol: 'Pm',
    name: 'Promethium',
    zh: '钷',
    mass: null,
    configuration: '[Xe]6s2 4f5',
  },
  {
    number: 62,
    symbol: 'Sm',
    name: 'Samarium',
    zh: '钐',
    mass: 150.36,
    configuration: '[Xe]6s2 4f6',
  },
  {
    number: 63,
    symbol: 'Eu',
    name: 'Europium',
    zh: '铕',
    mass: 151.96,
    configuration: '[Xe]6s2 4f7',
  },
  {
    number: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    zh: '钆',
    mass: 157.25,
    configuration: '[Xe]6s2 4f7 5d1',
  },
  {
    number: 65,
    symbol: 'Tb',
    name: 'Terbium',
    zh: '铽',
    mass: 158.93,
    configuration: '[Xe]6s2 4f9',
  },
  {
    number: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    zh: '镝',
    mass: 162.5,
    configuration: '[Xe]6s2 4f10',
  },
  {
    number: 67,
    symbol: 'Ho',
    name: 'Holmium',
    zh: '钬',
    mass: 164.93,
    configuration: '[Xe]6s2 4f11',
  },
  {
    number: 68,
    symbol: 'Er',
    name: 'Erbium',
    zh: '铒',
    mass: 167.26,
    configuration: '[Xe]6s2 4f12',
  },
  {
    number: 69,
    symbol: 'Tm',
    name: 'Thulium',
    zh: '铥',
    mass: 168.93,
    configuration: '[Xe]6s2 4f13',
  },
  {
    number: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    zh: '镱',
    mass: 173.05,
    configuration: '[Xe]6s2 4f14',
  },
  {
    number: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    zh: '镥',
    mass: 174.97,
    configuration: '[Xe]6s2 4f14 5d1',
  },
  {
    number: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    zh: '铪',
    mass: 178.49,
    configuration: '[Xe]6s2 4f14 5d2',
  },
  {
    number: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    zh: '钽',
    mass: 180.95,
    configuration: '[Xe]6s2 4f14 5d3',
  },
  {
    number: 74,
    symbol: 'W',
    name: 'Tungsten',
    zh: '钨',
    mass: 183.84,
    configuration: '[Xe]6s2 4f14 5d4',
  },
  {
    number: 75,
    symbol: 'Re',
    name: 'Rhenium',
    zh: '铼',
    mass: 186.21,
    configuration: '[Xe]6s2 4f14 5d5',
  },
  {
    number: 76,
    symbol: 'Os',
    name: 'Osmium',
    zh: '锇',
    mass: 190.23,
    configuration: '[Xe]6s2 4f14 5d6',
  },
  {
    number: 77,
    symbol: 'Ir',
    name: 'Iridium',
    zh: '铱',
    mass: 192.22,
    configuration: '[Xe]6s2 4f14 5d7',
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    zh: '铂',
    mass: 195.08,
    configuration: '[Xe]6s1 4f14 5d9',
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    zh: '金',
    mass: 196.97,
    configuration: '[Xe]6s1 4f14 5d10',
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    zh: '汞',
    mass: 200.59,
    configuration: '[Xe]6s2 4f14 5d10',
  },
  {
    number: 81,
    symbol: 'Tl',
    name: 'Thallium',
    zh: '铊',
    mass: 204.38,
    configuration: '[Xe]6s2 4f14 5d10 6p1',
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    zh: '铅',
    mass: 207.2,
    configuration: '[Xe]6s2 4f14 5d10 6p2',
  },
  {
    number: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    zh: '铋',
    mass: 208.98,
    configuration: '[Xe]6s2 4f14 5d10 6p3',
  },
  {
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    zh: '钋',
    mass: null,
    configuration: '[Xe]6s2 4f14 5d10 6p4',
  },
  {
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    zh: '砹',
    mass: null,
    configuration: '[Xe]6s2 4f14 5d10 6p5',
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    zh: '氡',
    mass: null,
    configuration: '[Xe]6s2 4f14 5d10 6p6',
  },
  {
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    zh: '钫',
    mass: null,
    configuration: '[Rn]7s1',
  },
  {
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    zh: '镭',
    mass: null,
    configuration: '[Rn]7s2',
  },
  {
    number: 89,
    symbol: 'Ac',
    name: 'Actinium',
    zh: '锕',
    mass: null,
    configuration: '[Rn]7s2 6d1',
  },
  {
    number: 90,
    symbol: 'Th',
    name: 'Thorium',
    zh: '钍',
    mass: 232.04,
    configuration: '[Rn]7s2 6d2',
  },
  {
    number: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    zh: '镤',
    mass: 231.04,
    configuration: '[Rn]7s2 5f2 6d1',
  },
  {
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    zh: '铀',
    mass: 238.03,
    configuration: '[Rn]7s2 5f3 6d1',
  },
  {
    number: 93,
    symbol: 'Np',
    name: 'Neptunium',
    zh: '镎',
    mass: null,
    configuration: '[Rn]7s2 5f4 6d1',
  },
  {
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    zh: '钚',
    mass: null,
    configuration: '[Rn]7s2 5f6',
  },
  {
    number: 95,
    symbol: 'Am',
    name: 'Americium',
    zh: '镅',
    mass: null,
    configuration: '[Rn]7s2 5f7',
  },
  {
    number: 96,
    symbol: 'Cm',
    name: 'Curium',
    zh: '锔',
    mass: null,
    configuration: '[Rn]7s2 5f7 6d1',
  },
  {
    number: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    zh: '锫',
    mass: null,
    configuration: '[Rn]7s2 5f9',
  },
  {
    number: 98,
    symbol: 'Cf',
    name: 'Californium',
    zh: '锎',
    mass: null,
    configuration: '[Rn]7s2 5f10',
  },
  {
    number: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    zh: '锿',
    mass: null,
    configuration: '[Rn]7s2 5f11',
  },
  {
    number: 100,
    symbol: 'Fm',
    name: 'Fermium',
    zh: '镄',
    mass: null,
    configuration: '[Rn] 5f12 7s2',
  },
  {
    number: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    zh: '钔',
    mass: null,
    configuration: '[Rn]7s2 5f13',
  },
  {
    number: 102,
    symbol: 'No',
    name: 'Nobelium',
    zh: '锘',
    mass: null,
    configuration: '[Rn]7s2 5f14',
  },
  {
    number: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    zh: '铹',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d1',
  },
  {
    number: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    zh: '𬬻',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d2',
  },
  {
    number: 105,
    symbol: 'Db',
    name: 'Dubnium',
    zh: '𬭊',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d3',
  },
  {
    number: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    zh: '𬭳',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d4',
  },
  {
    number: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    zh: '𬭛',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d5',
  },
  {
    number: 108,
    symbol: 'Hs',
    name: 'Hassium',
    zh: '𬭶',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d6',
  },
  {
    number: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    zh: '鿏',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d7 (calculated)',
  },
  {
    number: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    zh: '𫟼',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d8 (predicted)',
  },
  {
    number: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    zh: '𬬭',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d9 (predicted)',
  },
  {
    number: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    zh: '鿔',
    mass: null,
    configuration: '[Rn]7s2 5f14 6d10 (predicted)',
  },
  {
    number: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    zh: '鿭',
    mass: null,
    configuration: '[Rn]5f14 6d10 7s2 7p1 (predicted)',
  },
  {
    number: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    zh: '𫓧',
    mass: null,
    configuration: '[Rn]7s2 7p2 5f14 6d10 (predicted)',
  },
  {
    number: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    zh: '镆',
    mass: null,
    configuration: '[Rn]7s2 7p3 5f14 6d10 (predicted)',
  },
  {
    number: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    zh: '𫟷',
    mass: null,
    configuration: '[Rn]7s2 7p4 5f14 6d10 (predicted)',
  },
  {
    number: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    zh: '鿬',
    mass: null,
    configuration: '[Rn]7s2 7p5 5f14 6d10 (predicted)',
  },
  {
    number: 118,
    symbol: 'Og',
    name: 'Oganesson',
    zh: '鿫',
    mass: null,
    configuration: '[Rn]7s2 7p6 5f14 6d10 (predicted)',
  },
];
