import {
  BookOpen,
  CalendarCheck,
  CircuitBoard,
  CookingPot,
  CopyCheck,
  Drum,
  FileCode2,
  Files,
  FolderSync,
  Grid2X2,
  Grid3X3,
  Guitar,
  Network,
  PenTool,
  Piano,
  Presentation,
  Scissors,
  SpellCheck,
  Spline,
  Timer,
} from 'lucide-react';
export const PRACTICAL_TOOLS = [
  { id: 'pdf-compare', icon: Files, color: 'text-blue-500' },
  { id: 'folder-compare', icon: FolderSync, color: 'text-emerald-500' },
  { id: 'duplicate-files', icon: CopyCheck, color: 'text-amber-500' },
  { id: 'mind-map', icon: Network, color: 'text-violet-500' },
  { id: 'whiteboard', icon: PenTool, color: 'text-cyan-500' },
  { id: 'markdown-slides', icon: Presentation, color: 'text-rose-500' },
  { id: 'pdf-booklet', icon: BookOpen, color: 'text-orange-500' },
  { id: 'text-encoding', icon: FileCode2, color: 'text-teal-500' },
  { id: 'image-vectorizer', icon: Spline, color: 'text-fuchsia-500' },
  { id: 'sprite-sheet', icon: Grid2X2, color: 'text-sky-500' },
  { id: 'clip-path-editor', icon: Scissors, color: 'text-indigo-500' },
  { id: 'resistor-code', icon: CircuitBoard, color: 'text-green-500' },
  { id: 'chess-clock', icon: Timer, color: 'text-purple-500' },
  { id: 'piano', icon: Piano, color: 'text-pink-500' },
  { id: 'chord-tool', icon: Guitar, color: 'text-lime-500' },
  { id: 'drum-machine', icon: Drum, color: 'text-red-500' },
  { id: 'habit-tracker', icon: CalendarCheck, color: 'text-yellow-500' },
  { id: 'meal-planner', icon: CookingPot, color: 'text-slate-500' },
  { id: 'sudoku', icon: Grid3X3, color: 'text-stone-500' },
  { id: 'word-search', icon: SpellCheck, color: 'text-zinc-500' },
] as const;
export type PracticalToolId = (typeof PRACTICAL_TOOLS)[number]['id'];
