import {
  BookSearch,
  Wallet,
  Camera,
  Scissors,
  Sprout,
  FlaskConical,
  Orbit,
} from 'lucide-react';
export const PRACTICAL_SCIENCE_TOOLS = [
  {
    id: 'document-search',
    icon: BookSearch,
    color: 'text-sky-500',
    titleKey: 'documentWorkspaces.searchTitle',
    descKey: 'documentWorkspaces.searchDesc',
    keywords: '文档 全文 搜索 TXT Markdown PDF DOCX document search',
  },
  {
    id: 'expense-ledger',
    icon: Wallet,
    color: 'text-emerald-500',
    titleKey: 'organizerTools.ledger.title',
    descKey: 'organizerTools.ledger.description',
    keywords: '记账 账本 收支 预算 转账 账户 expense ledger budget',
  },
  {
    id: 'photography-toolbox',
    icon: Camera,
    color: 'text-amber-500',
    titleKey: 'scienceTools.tools.photography.title',
    descKey: 'scienceTools.tools.photography.description',
    keywords: '摄影 景深 超焦距 曝光 ND 日出 黄金时刻 photography exposure',
  },
  {
    id: 'sewing-pattern',
    icon: Scissors,
    color: 'text-pink-500',
    titleKey: 'scienceTools.tools.sewing.title',
    descKey: 'scienceTools.tools.sewing.description',
    keywords: '缝纫 纸样 裙 围裙 布袋 sewing pattern',
  },
  {
    id: 'garden-planner',
    icon: Sprout,
    color: 'text-lime-500',
    titleKey: 'organizerTools.garden.title',
    descKey: 'organizerTools.garden.description',
    keywords: '园艺 菜园 播种 育苗 移栽 株距 garden planting',
  },
  {
    id: 'chemistry-toolbox',
    icon: FlaskConical,
    color: 'text-violet-500',
    titleKey: 'scienceTools.tools.chemistry.title',
    descKey: 'scienceTools.tools.chemistry.description',
    keywords: '化学 元素 周期表 摩尔 配平 浓度 稀释 chemistry molar',
  },
  {
    id: 'physics-toolbox',
    icon: Orbit,
    color: 'text-cyan-500',
    titleKey: 'scienceTools.tools.physics.title',
    descKey: 'scienceTools.tools.physics.description',
    keywords: '物理 运动 力 功 能 热 气体 透镜 physics',
  },
] as const;
export const PRACTICAL_SCIENCE_KEYWORDS: Record<string, string> = {
  '/csv-convert':
    '清洗 拆列 合列 空值 日期 相似归并 撤销 clean split merge cluster',
  '/document-maker': '批量 证书 通知 编号 CSV 变量 ZIP batch certificates',
  '/pdf-toolkit': '裁切 页眉 页脚 页码 纸张 脱敏 redact crop',
  '/ebook-reader': '电子书 制作 编辑 章节 封面 EPUB create edit',
  '/image-compare': '选片 评分 淘汰 留片 ZIP cull rate',
  '/image-privacy': 'EXIF 作者 版权 拍摄日期 批量 写入 metadata',
  '/video-editor': '分镜 联系表 抽帧 时间码 注释 storyboard contact sheet',
  '/piano': 'MIDI 钢琴卷帘 多轨 作曲 量化 移调 velocity compose',
  '/audio-editor': '频谱 频谱图 RMS 响度 削波 相关性 spectrum spectrogram',
  '/gltf-inspector': 'G-code 层 挤出 空移 速度 耗材 gcode slicer',
  '/shift-calendar': '工时 打卡 休息 跨夜 项目 实际 actual timesheet',
  '/ics-generator': '合并 去重 冲突 空闲 筛选 ICS merge conflicts free time',
  '/word-search': '题册 填字 迷宫 数织 答案 crossword maze nonogram',
};
